.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

/* Handwritten function */
nonmatching entrypoint, 0x3C

glabel entrypoint
    /* 1000 80070C00 3C08800B */  lui        $t0, %hi(main_BSS_START)
    /* 1004 80070C04 2508EDB0 */  addiu      $t0, $t0, %lo(main_BSS_START)
    /* 1008 80070C08 3C090004 */  lui        $t1, %hi(main_BSS_SIZE)
    /* 100C 80070C0C 2529AE70 */  addiu      $t1, $t1, %lo(main_BSS_SIZE)
  .L80070C10:
    /* 1010 80070C10 AD000000 */  sw         $zero, 0x0($t0)
    /* 1014 80070C14 AD000004 */  sw         $zero, 0x4($t0)
    /* 1018 80070C18 21080008 */  addi       $t0, $t0, 0x8 /* handwritten instruction */
    /* 101C 80070C1C 2129FFF8 */  addi       $t1, $t1, -0x8 /* handwritten instruction */
    /* 1020 80070C20 1520FFFB */  bnez       $t1, .L80070C10
    /* 1024 80070C24 00000000 */   nop
    /* 1028 80070C28 3C0A8008 */  lui        $t2, %hi(main)
    /* 102C 80070C2C 254AF880 */  addiu      $t2, $t2, %lo(main)
    /* 1030 80070C30 3C1D800C */  lui        $sp, %hi(D_800C6D60)
    /* 1034 80070C34 01400008 */  jr         $t2
    /* 1038 80070C38 27BD6D60 */   addiu     $sp, $sp, %lo(D_800C6D60)
endlabel entrypoint
    /* 103C 80070C3C 00000000 */  nop
    /* 1040 80070C40 00000000 */  nop
    /* 1044 80070C44 00000000 */  nop
    /* 1048 80070C48 00000000 */  nop
    /* 104C 80070C4C 00000000 */  nop
    /* 1050 80070C50 00000000 */  nop
    /* 1054 80070C54 00000000 */  nop
    /* 1058 80070C58 00000000 */  nop
    /* 105C 80070C5C 00000000 */  nop
