.include "macro.inc"

.set noat
.set noreorder
.set gp=64

.section .text, "ax"

/* Generated by spimdisasm 1.42.4 */

nonmatching func_800E9C20, 0xCC

glabel func_800E9C20
    /* 3F1B0 800E9C20 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3F1B4 800E9C24 3C04002C */  lui        $a0, %hi(D_002B8B70)
    /* 3F1B8 800E9C28 24848B70 */  addiu      $a0, $a0, %lo(D_002B8B70)
    /* 3F1BC 800E9C2C AFB20018 */  sw         $s2, 0x18($sp)
    /* 3F1C0 800E9C30 3C128016 */  lui        $s2, %hi(D_80164770)
    /* 3F1C4 800E9C34 26524770 */  addiu      $s2, $s2, %lo(D_80164770)
    /* 3F1C8 800E9C38 02402821 */  addu       $a1, $s2, $zero
    /* 3F1CC 800E9C3C 3C06002C */  lui        $a2, %hi(D_002BF220)
    /* 3F1D0 800E9C40 24C6F220 */  addiu      $a2, $a2, %lo(D_002BF220)
    /* 3F1D4 800E9C44 00C43023 */  subu       $a2, $a2, $a0
    /* 3F1D8 800E9C48 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3F1DC 800E9C4C AFB10014 */  sw         $s1, 0x14($sp)
    /* 3F1E0 800E9C50 0C0227E0 */  jal        func_80089F80
    /* 3F1E4 800E9C54 AFB00010 */   sw        $s0, 0x10($sp)
    /* 3F1E8 800E9C58 3C040042 */  lui        $a0, %hi(D_00423FC0)
    /* 3F1EC 800E9C5C 24843FC0 */  addiu      $a0, $a0, %lo(D_00423FC0)
    /* 3F1F0 800E9C60 3C118010 */  lui        $s1, %hi(D_80104710)
    /* 3F1F4 800E9C64 26314710 */  addiu      $s1, $s1, %lo(D_80104710)
    /* 3F1F8 800E9C68 02202821 */  addu       $a1, $s1, $zero
    /* 3F1FC 800E9C6C 3C060043 */  lui        $a2, %hi(D_00429CA0)
    /* 3F200 800E9C70 24C69CA0 */  addiu      $a2, $a2, %lo(D_00429CA0)
    /* 3F204 800E9C74 0C0227E0 */  jal        func_80089F80
    /* 3F208 800E9C78 00C43023 */   subu      $a2, $a2, $a0
    /* 3F20C 800E9C7C 3C04004E */  lui        $a0, %hi(D_004E3110)
    /* 3F210 800E9C80 24843110 */  addiu      $a0, $a0, %lo(D_004E3110)
    /* 3F214 800E9C84 3C108011 */  lui        $s0, %hi(D_8010A760)
    /* 3F218 800E9C88 2610A760 */  addiu      $s0, $s0, %lo(D_8010A760)
    /* 3F21C 800E9C8C 02002821 */  addu       $a1, $s0, $zero
    /* 3F220 800E9C90 3C06004F */  lui        $a2, %hi(D_004F0F80)
    /* 3F224 800E9C94 24C60F80 */  addiu      $a2, $a2, %lo(D_004F0F80)
    /* 3F228 800E9C98 0C0227E0 */  jal        func_80089F80
    /* 3F22C 800E9C9C 00C43023 */   subu      $a2, $a2, $a0
    /* 3F230 800E9CA0 3C05002C */  lui        $a1, %hi(D_002BF220)
    /* 3F234 800E9CA4 24A5F220 */  addiu      $a1, $a1, %lo(D_002BF220)
    /* 3F238 800E9CA8 0C02076D */  jal        func_80081DB4
    /* 3F23C 800E9CAC 02402021 */   addu      $a0, $s2, $zero
    /* 3F240 800E9CB0 3C050043 */  lui        $a1, %hi(D_00429CA0)
    /* 3F244 800E9CB4 24A59CA0 */  addiu      $a1, $a1, %lo(D_00429CA0)
    /* 3F248 800E9CB8 0C02076D */  jal        func_80081DB4
    /* 3F24C 800E9CBC 02202021 */   addu      $a0, $s1, $zero
    /* 3F250 800E9CC0 0C0207DF */  jal        func_80081F7C
    /* 3F254 800E9CC4 02002021 */   addu      $a0, $s0, $zero
    /* 3F258 800E9CC8 02002021 */  addu       $a0, $s0, $zero
    /* 3F25C 800E9CCC 0C02080B */  jal        func_8008202C
    /* 3F260 800E9CD0 02202821 */   addu      $a1, $s1, $zero
    /* 3F264 800E9CD4 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3F268 800E9CD8 8FB20018 */  lw         $s2, 0x18($sp)
    /* 3F26C 800E9CDC 8FB10014 */  lw         $s1, 0x14($sp)
    /* 3F270 800E9CE0 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3F274 800E9CE4 03E00008 */  jr         $ra
    /* 3F278 800E9CE8 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800E9C20

nonmatching func_800E9CEC, 0x148

glabel func_800E9CEC
    /* 3F27C 800E9CEC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3F280 800E9CF0 3C050004 */  lui        $a1, (0x4C000 >> 16)
    /* 3F284 800E9CF4 34A5C000 */  ori        $a1, $a1, (0x4C000 & 0xFFFF)
    /* 3F288 800E9CF8 3C048011 */  lui        $a0, %hi(D_8010A710)
    /* 3F28C 800E9CFC 2484A710 */  addiu      $a0, $a0, %lo(D_8010A710)
    /* 3F290 800E9D00 3C03800F */  lui        $v1, %hi(D_800EBB00)
    /* 3F294 800E9D04 2463BB00 */  addiu      $v1, $v1, %lo(D_800EBB00)
    /* 3F298 800E9D08 3402A800 */  ori        $v0, $zero, 0xA800
    /* 3F29C 800E9D0C 00621021 */  addu       $v0, $v1, $v0
    /* 3F2A0 800E9D10 3C018017 */  lui        $at, %hi(D_8016AF70)
    /* 3F2A4 800E9D14 AC22AF70 */  sw         $v0, %lo(D_8016AF70)($at)
    /* 3F2A8 800E9D18 3C018010 */  lui        $at, %hi(D_80104700)
    /* 3F2AC 800E9D1C AC224700 */  sw         $v0, %lo(D_80104700)($at)
    /* 3F2B0 800E9D20 3C01800F */  lui        $at, %hi(D_800EB148)
    /* 3F2B4 800E9D24 AC22B148 */  sw         $v0, %lo(D_800EB148)($at)
    /* 3F2B8 800E9D28 3C01800F */  lui        $at, %hi(D_800EB198)
    /* 3F2BC 800E9D2C AC22B198 */  sw         $v0, %lo(D_800EB198)($at)
    /* 3F2C0 800E9D30 2402FFFF */  addiu      $v0, $zero, -0x1
    /* 3F2C4 800E9D34 3C01800F */  lui        $at, %hi(D_800EB268)
    /* 3F2C8 800E9D38 AC22B268 */  sw         $v0, %lo(D_800EB268)($at)
    /* 3F2CC 800E9D3C 3C01800F */  lui        $at, %hi(D_800EB2B8)
    /* 3F2D0 800E9D40 AC22B2B8 */  sw         $v0, %lo(D_800EB2B8)($at)
    /* 3F2D4 800E9D44 24020020 */  addiu      $v0, $zero, 0x20
    /* 3F2D8 800E9D48 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3F2DC 800E9D4C 3C01800F */  lui        $at, %hi(D_800EB0F8)
    /* 3F2E0 800E9D50 AC23B0F8 */  sw         $v1, %lo(D_800EB0F8)($at)
    /* 3F2E4 800E9D54 AC800000 */  sw         $zero, 0x0($a0)
    /* 3F2E8 800E9D58 3C018011 */  lui        $at, %hi(D_8010A714)
    /* 3F2EC 800E9D5C AC22A714 */  sw         $v0, %lo(D_8010A714)($at)
    /* 3F2F0 800E9D60 24020046 */  addiu      $v0, $zero, 0x46
    /* 3F2F4 800E9D64 3C018011 */  lui        $at, %hi(D_8010A71C)
    /* 3F2F8 800E9D68 AC22A71C */  sw         $v0, %lo(D_8010A71C)($at)
    /* 3F2FC 800E9D6C 3C028012 */  lui        $v0, %hi(D_80118760)
    /* 3F300 800E9D70 24428760 */  addiu      $v0, $v0, %lo(D_80118760)
    /* 3F304 800E9D74 3C018011 */  lui        $at, %hi(D_8010A720)
    /* 3F308 800E9D78 AC22A720 */  sw         $v0, %lo(D_8010A720)($at)
    /* 3F30C 800E9D7C 3C028016 */  lui        $v0, %hi(D_80164770)
    /* 3F310 800E9D80 24424770 */  addiu      $v0, $v0, %lo(D_80164770)
    /* 3F314 800E9D84 3C018011 */  lui        $at, %hi(D_8010A728)
    /* 3F318 800E9D88 AC22A728 */  sw         $v0, %lo(D_8010A728)($at)
    /* 3F31C 800E9D8C 3C02002C */  lui        $v0, %hi(D_002BF220)
    /* 3F320 800E9D90 2442F220 */  addiu      $v0, $v0, %lo(D_002BF220)
    /* 3F324 800E9D94 3C018011 */  lui        $at, %hi(D_8010A72C)
    /* 3F328 800E9D98 AC22A72C */  sw         $v0, %lo(D_8010A72C)($at)
    /* 3F32C 800E9D9C 24020040 */  addiu      $v0, $zero, 0x40
    /* 3F330 800E9DA0 3C018011 */  lui        $at, %hi(D_8010A734)
    /* 3F334 800E9DA4 AC22A734 */  sw         $v0, %lo(D_8010A734)($at)
    /* 3F338 800E9DA8 24020100 */  addiu      $v0, $zero, 0x100
    /* 3F33C 800E9DAC 3C018011 */  lui        $at, %hi(D_8010A738)
    /* 3F340 800E9DB0 AC22A738 */  sw         $v0, %lo(D_8010A738)($at)
    /* 3F344 800E9DB4 24027D00 */  addiu      $v0, $zero, 0x7D00
    /* 3F348 800E9DB8 3C018011 */  lui        $at, %hi(D_8010A73C)
    /* 3F34C 800E9DBC AC22A73C */  sw         $v0, %lo(D_8010A73C)($at)
    /* 3F350 800E9DC0 24021000 */  addiu      $v0, $zero, 0x1000
    /* 3F354 800E9DC4 3C018011 */  lui        $at, %hi(D_8010A740)
    /* 3F358 800E9DC8 AC22A740 */  sw         $v0, %lo(D_8010A740)($at)
    /* 3F35C 800E9DCC 24020001 */  addiu      $v0, $zero, 0x1
    /* 3F360 800E9DD0 3C018011 */  lui        $at, %hi(D_8010A744)
    /* 3F364 800E9DD4 AC22A744 */  sw         $v0, %lo(D_8010A744)($at)
    /* 3F368 800E9DD8 24020048 */  addiu      $v0, $zero, 0x48
    /* 3F36C 800E9DDC 3C018011 */  lui        $at, %hi(D_8010A748)
    /* 3F370 800E9DE0 AC22A748 */  sw         $v0, %lo(D_8010A748)($at)
    /* 3F374 800E9DE4 240203C0 */  addiu      $v0, $zero, 0x3C0
    /* 3F378 800E9DE8 3C018017 */  lui        $at, %hi(D_8016AF74)
    /* 3F37C 800E9DEC AC23AF74 */  sw         $v1, %lo(D_8016AF74)($at)
    /* 3F380 800E9DF0 3C018016 */  lui        $at, %hi(D_80164760)
    /* 3F384 800E9DF4 AC204760 */  sw         $zero, %lo(D_80164760)($at)
    /* 3F388 800E9DF8 3C018011 */  lui        $at, %hi(D_8010A718)
    /* 3F38C 800E9DFC AC20A718 */  sw         $zero, %lo(D_8010A718)($at)
    /* 3F390 800E9E00 3C018011 */  lui        $at, %hi(D_8010A724)
    /* 3F394 800E9E04 AC25A724 */  sw         $a1, %lo(D_8010A724)($at)
    /* 3F398 800E9E08 3C018011 */  lui        $at, %hi(D_8010A730)
    /* 3F39C 800E9E0C AC20A730 */  sw         $zero, %lo(D_8010A730)($at)
    /* 3F3A0 800E9E10 3C018011 */  lui        $at, %hi(D_8010A74C)
    /* 3F3A4 800E9E14 0C020370 */  jal        func_80080DC0
    /* 3F3A8 800E9E18 AC22A74C */   sw        $v0, %lo(D_8010A74C)($at)
    /* 3F3AC 800E9E1C 3C048008 */  lui        $a0, %hi(func_80081080)
    /* 3F3B0 800E9E20 0C020410 */  jal        func_80081040
    /* 3F3B4 800E9E24 24841080 */   addiu     $a0, $a0, %lo(func_80081080)
    /* 3F3B8 800E9E28 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3F3BC 800E9E2C 03E00008 */  jr         $ra
    /* 3F3C0 800E9E30 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800E9CEC

nonmatching func_800E9E34, 0x2B0

glabel func_800E9E34
    /* 3F3C4 800E9E34 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3F3C8 800E9E38 AFB00010 */  sw         $s0, 0x10($sp)
    /* 3F3CC 800E9E3C 3C10800F */  lui        $s0, %hi(D_800EB0B0)
    /* 3F3D0 800E9E40 2610B0B0 */  addiu      $s0, $s0, %lo(D_800EB0B0)
    /* 3F3D4 800E9E44 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3F3D8 800E9E48 0C03A839 */  jal        func_800EA0E4
    /* 3F3DC 800E9E4C 02002021 */   addu      $a0, $s0, $zero
    /* 3F3E0 800E9E50 3C04800F */  lui        $a0, %hi(D_800EB100)
    /* 3F3E4 800E9E54 0C03A839 */  jal        func_800EA0E4
    /* 3F3E8 800E9E58 2484B100 */   addiu     $a0, $a0, %lo(D_800EB100)
    /* 3F3EC 800E9E5C 3C04800F */  lui        $a0, %hi(D_800EB150)
    /* 3F3F0 800E9E60 0C03A839 */  jal        func_800EA0E4
    /* 3F3F4 800E9E64 2484B150 */   addiu     $a0, $a0, %lo(D_800EB150)
    /* 3F3F8 800E9E68 3C04800F */  lui        $a0, %hi(D_800EB1A0)
    /* 3F3FC 800E9E6C 0C03A839 */  jal        func_800EA0E4
    /* 3F400 800E9E70 2484B1A0 */   addiu     $a0, $a0, %lo(D_800EB1A0)
    /* 3F404 800E9E74 3C04800F */  lui        $a0, %hi(D_800EB1F0)
    /* 3F408 800E9E78 0C03A839 */  jal        func_800EA0E4
    /* 3F40C 800E9E7C 2484B1F0 */   addiu     $a0, $a0, %lo(D_800EB1F0)
    /* 3F410 800E9E80 3C04800F */  lui        $a0, %hi(D_800EB240)
    /* 3F414 800E9E84 0C03A839 */  jal        func_800EA0E4
    /* 3F418 800E9E88 2484B240 */   addiu     $a0, $a0, %lo(D_800EB240)
    /* 3F41C 800E9E8C 3C04800F */  lui        $a0, %hi(D_800EB290)
    /* 3F420 800E9E90 0C03A839 */  jal        func_800EA0E4
    /* 3F424 800E9E94 2484B290 */   addiu     $a0, $a0, %lo(D_800EB290)
    /* 3F428 800E9E98 3C02800F */  lui        $v0, %hi(D_800EB0E8)
    /* 3F42C 800E9E9C 8C42B0E8 */  lw         $v0, %lo(D_800EB0E8)($v0)
    /* 3F430 800E9EA0 10400021 */  beqz       $v0, .L800E9F28
    /* 3F434 800E9EA4 00000000 */   nop
    /* 3F438 800E9EA8 3C02800F */  lui        $v0, %hi(D_800EB0EC)
    /* 3F43C 800E9EAC 8C42B0EC */  lw         $v0, %lo(D_800EB0EC)($v0)
    /* 3F440 800E9EB0 1040001D */  beqz       $v0, .L800E9F28
    /* 3F444 800E9EB4 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F448 800E9EB8 3C01800F */  lui        $at, %hi(D_800EB0EC)
    /* 3F44C 800E9EBC 1440001A */  bnez       $v0, .L800E9F28
    /* 3F450 800E9EC0 AC22B0EC */   sw        $v0, %lo(D_800EB0EC)($at)
    /* 3F454 800E9EC4 3C04800F */  lui        $a0, %hi(D_800EB0D4)
    /* 3F458 800E9EC8 0C0206C2 */  jal        func_80081B08
    /* 3F45C 800E9ECC 8C84B0D4 */   lw        $a0, %lo(D_800EB0D4)($a0)
    /* 3F460 800E9ED0 10400009 */  beqz       $v0, .L800E9EF8
    /* 3F464 800E9ED4 24020002 */   addiu     $v0, $zero, 0x2
    /* 3F468 800E9ED8 3C04800F */  lui        $a0, %hi(D_800EB0D4)
    /* 3F46C 800E9EDC 8C84B0D4 */  lw         $a0, %lo(D_800EB0D4)($a0)
    /* 3F470 800E9EE0 0C020695 */  jal        func_80081A54
    /* 3F474 800E9EE4 00002821 */   addu      $a1, $zero, $zero
    /* 3F478 800E9EE8 24020001 */  addiu      $v0, $zero, 0x1
    /* 3F47C 800E9EEC 3C01800F */  lui        $at, %hi(D_800EB0EC)
    /* 3F480 800E9EF0 0803A7CA */  j          .L800E9F28
    /* 3F484 800E9EF4 AC22B0EC */   sw        $v0, %lo(D_800EB0EC)($at)
  .L800E9EF8:
    /* 3F488 800E9EF8 3C03800F */  lui        $v1, %hi(D_800EB0E8)
    /* 3F48C 800E9EFC 8C63B0E8 */  lw         $v1, %lo(D_800EB0E8)($v1)
    /* 3F490 800E9F00 14620009 */  bne        $v1, $v0, .L800E9F28
    /* 3F494 800E9F04 00000000 */   nop
    /* 3F498 800E9F08 3C02800F */  lui        $v0, %hi(D_800EB0F0)
    /* 3F49C 800E9F0C 8C42B0F0 */  lw         $v0, %lo(D_800EB0F0)($v0)
    /* 3F4A0 800E9F10 3C01800F */  lui        $at, %hi(D_800EB0E8)
    /* 3F4A4 800E9F14 AC20B0E8 */  sw         $zero, %lo(D_800EB0E8)($at)
    /* 3F4A8 800E9F18 3C01800F */  lui        $at, %hi(D_800EB0DC)
    /* 3F4AC 800E9F1C AC22B0DC */  sw         $v0, %lo(D_800EB0DC)($at)
    /* 3F4B0 800E9F20 0C03A922 */  jal        func_800EA488
    /* 3F4B4 800E9F24 02002021 */   addu      $a0, $s0, $zero
  .L800E9F28:
    /* 3F4B8 800E9F28 3C05800F */  lui        $a1, %hi(D_800EB138)
    /* 3F4BC 800E9F2C 24A5B138 */  addiu      $a1, $a1, %lo(D_800EB138)
    /* 3F4C0 800E9F30 8CA30000 */  lw         $v1, 0x0($a1)
    /* 3F4C4 800E9F34 10600012 */  beqz       $v1, .L800E9F80
    /* 3F4C8 800E9F38 00000000 */   nop
    /* 3F4CC 800E9F3C 3C02800F */  lui        $v0, %hi(D_800EB13C)
    /* 3F4D0 800E9F40 8C42B13C */  lw         $v0, %lo(D_800EB13C)($v0)
    /* 3F4D4 800E9F44 1040000E */  beqz       $v0, .L800E9F80
    /* 3F4D8 800E9F48 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F4DC 800E9F4C 3C01800F */  lui        $at, %hi(D_800EB13C)
    /* 3F4E0 800E9F50 AC22B13C */  sw         $v0, %lo(D_800EB13C)($at)
    /* 3F4E4 800E9F54 1440000A */  bnez       $v0, .L800E9F80
    /* 3F4E8 800E9F58 24020002 */   addiu     $v0, $zero, 0x2
    /* 3F4EC 800E9F5C 14620008 */  bne        $v1, $v0, .L800E9F80
    /* 3F4F0 800E9F60 00000000 */   nop
    /* 3F4F4 800E9F64 3C02800F */  lui        $v0, %hi(D_800EB140)
    /* 3F4F8 800E9F68 8C42B140 */  lw         $v0, %lo(D_800EB140)($v0)
    /* 3F4FC 800E9F6C ACA00000 */  sw         $zero, 0x0($a1)
    /* 3F500 800E9F70 3C01800F */  lui        $at, %hi(D_800EB12C)
    /* 3F504 800E9F74 AC22B12C */  sw         $v0, %lo(D_800EB12C)($at)
    /* 3F508 800E9F78 0C03A922 */  jal        func_800EA488
    /* 3F50C 800E9F7C 24A4FFC8 */   addiu     $a0, $a1, -0x38
  .L800E9F80:
    /* 3F510 800E9F80 3C05800F */  lui        $a1, %hi(D_800EB188)
    /* 3F514 800E9F84 24A5B188 */  addiu      $a1, $a1, %lo(D_800EB188)
    /* 3F518 800E9F88 8CA30000 */  lw         $v1, 0x0($a1)
    /* 3F51C 800E9F8C 10600011 */  beqz       $v1, .L800E9FD4
    /* 3F520 800E9F90 00000000 */   nop
    /* 3F524 800E9F94 3C02800F */  lui        $v0, %hi(D_800EB18C)
    /* 3F528 800E9F98 8C42B18C */  lw         $v0, %lo(D_800EB18C)($v0)
    /* 3F52C 800E9F9C 1040000D */  beqz       $v0, .L800E9FD4
    /* 3F530 800E9FA0 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F534 800E9FA4 3C01800F */  lui        $at, %hi(D_800EB18C)
    /* 3F538 800E9FA8 AC22B18C */  sw         $v0, %lo(D_800EB18C)($at)
    /* 3F53C 800E9FAC 14400015 */  bnez       $v0, .L800EA004
    /* 3F540 800E9FB0 24020002 */   addiu     $v0, $zero, 0x2
    /* 3F544 800E9FB4 14620013 */  bne        $v1, $v0, .L800EA004
    /* 3F548 800E9FB8 24A4FFC8 */   addiu     $a0, $a1, -0x38
    /* 3F54C 800E9FBC 3C02800F */  lui        $v0, %hi(D_800EB190)
    /* 3F550 800E9FC0 8C42B190 */  lw         $v0, %lo(D_800EB190)($v0)
    /* 3F554 800E9FC4 ACA00000 */  sw         $zero, 0x0($a1)
    /* 3F558 800E9FC8 3C01800F */  lui        $at, %hi(D_800EB17C)
    /* 3F55C 800E9FCC 0803A7FF */  j          .L800E9FFC
    /* 3F560 800E9FD0 AC22B17C */   sw        $v0, %lo(D_800EB17C)($at)
  .L800E9FD4:
    /* 3F564 800E9FD4 3C10800F */  lui        $s0, %hi(D_800EB17C)
    /* 3F568 800E9FD8 2610B17C */  addiu      $s0, $s0, %lo(D_800EB17C)
    /* 3F56C 800E9FDC 8E020000 */  lw         $v0, 0x0($s0)
    /* 3F570 800E9FE0 10400008 */  beqz       $v0, .L800EA004
    /* 3F574 800E9FE4 00000000 */   nop
    /* 3F578 800E9FE8 3C04800F */  lui        $a0, %hi(D_800EB174)
    /* 3F57C 800E9FEC 0C0206C2 */  jal        func_80081B08
    /* 3F580 800E9FF0 8C84B174 */   lw        $a0, %lo(D_800EB174)($a0)
    /* 3F584 800E9FF4 14400003 */  bnez       $v0, .L800EA004
    /* 3F588 800E9FF8 2604FFD4 */   addiu     $a0, $s0, -0x2C
  .L800E9FFC:
    /* 3F58C 800E9FFC 0C03A922 */  jal        func_800EA488
    /* 3F590 800EA000 00000000 */   nop
  .L800EA004:
    /* 3F594 800EA004 3C05800F */  lui        $a1, %hi(D_800EB1D8)
    /* 3F598 800EA008 24A5B1D8 */  addiu      $a1, $a1, %lo(D_800EB1D8)
    /* 3F59C 800EA00C 8CA30000 */  lw         $v1, 0x0($a1)
    /* 3F5A0 800EA010 10600012 */  beqz       $v1, .L800EA05C
    /* 3F5A4 800EA014 00000000 */   nop
    /* 3F5A8 800EA018 3C02800F */  lui        $v0, %hi(D_800EB1DC)
    /* 3F5AC 800EA01C 8C42B1DC */  lw         $v0, %lo(D_800EB1DC)($v0)
    /* 3F5B0 800EA020 1040000E */  beqz       $v0, .L800EA05C
    /* 3F5B4 800EA024 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F5B8 800EA028 3C01800F */  lui        $at, %hi(D_800EB1DC)
    /* 3F5BC 800EA02C AC22B1DC */  sw         $v0, %lo(D_800EB1DC)($at)
    /* 3F5C0 800EA030 1440000A */  bnez       $v0, .L800EA05C
    /* 3F5C4 800EA034 24020002 */   addiu     $v0, $zero, 0x2
    /* 3F5C8 800EA038 14620008 */  bne        $v1, $v0, .L800EA05C
    /* 3F5CC 800EA03C 00000000 */   nop
    /* 3F5D0 800EA040 3C02800F */  lui        $v0, %hi(D_800EB1E0)
    /* 3F5D4 800EA044 8C42B1E0 */  lw         $v0, %lo(D_800EB1E0)($v0)
    /* 3F5D8 800EA048 ACA00000 */  sw         $zero, 0x0($a1)
    /* 3F5DC 800EA04C 3C01800F */  lui        $at, %hi(D_800EB1CC)
    /* 3F5E0 800EA050 AC22B1CC */  sw         $v0, %lo(D_800EB1CC)($at)
    /* 3F5E4 800EA054 0C03A922 */  jal        func_800EA488
    /* 3F5E8 800EA058 24A4FFC8 */   addiu     $a0, $a1, -0x38
  .L800EA05C:
    /* 3F5EC 800EA05C 3C02800F */  lui        $v0, %hi(D_800EB228)
    /* 3F5F0 800EA060 8C42B228 */  lw         $v0, %lo(D_800EB228)($v0)
    /* 3F5F4 800EA064 10400007 */  beqz       $v0, .L800EA084
    /* 3F5F8 800EA068 00000000 */   nop
    /* 3F5FC 800EA06C 3C02800F */  lui        $v0, %hi(D_800EB22C)
    /* 3F600 800EA070 8C42B22C */  lw         $v0, %lo(D_800EB22C)($v0)
    /* 3F604 800EA074 10400003 */  beqz       $v0, .L800EA084
    /* 3F608 800EA078 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F60C 800EA07C 3C01800F */  lui        $at, %hi(D_800EB22C)
    /* 3F610 800EA080 AC22B22C */  sw         $v0, %lo(D_800EB22C)($at)
  .L800EA084:
    /* 3F614 800EA084 3C02800F */  lui        $v0, %hi(D_800EB278)
    /* 3F618 800EA088 8C42B278 */  lw         $v0, %lo(D_800EB278)($v0)
    /* 3F61C 800EA08C 10400007 */  beqz       $v0, .L800EA0AC
    /* 3F620 800EA090 00000000 */   nop
    /* 3F624 800EA094 3C02800F */  lui        $v0, %hi(D_800EB27C)
    /* 3F628 800EA098 8C42B27C */  lw         $v0, %lo(D_800EB27C)($v0)
    /* 3F62C 800EA09C 10400003 */  beqz       $v0, .L800EA0AC
    /* 3F630 800EA0A0 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F634 800EA0A4 3C01800F */  lui        $at, %hi(D_800EB27C)
    /* 3F638 800EA0A8 AC22B27C */  sw         $v0, %lo(D_800EB27C)($at)
  .L800EA0AC:
    /* 3F63C 800EA0AC 3C02800F */  lui        $v0, %hi(D_800EB2C8)
    /* 3F640 800EA0B0 8C42B2C8 */  lw         $v0, %lo(D_800EB2C8)($v0)
    /* 3F644 800EA0B4 10400007 */  beqz       $v0, .L800EA0D4
    /* 3F648 800EA0B8 00000000 */   nop
    /* 3F64C 800EA0BC 3C02800F */  lui        $v0, %hi(D_800EB2CC)
    /* 3F650 800EA0C0 8C42B2CC */  lw         $v0, %lo(D_800EB2CC)($v0)
    /* 3F654 800EA0C4 10400003 */  beqz       $v0, .L800EA0D4
    /* 3F658 800EA0C8 2442FFFF */   addiu     $v0, $v0, -0x1
    /* 3F65C 800EA0CC 3C01800F */  lui        $at, %hi(D_800EB2CC)
    /* 3F660 800EA0D0 AC22B2CC */  sw         $v0, %lo(D_800EB2CC)($at)
  .L800EA0D4:
    /* 3F664 800EA0D4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3F668 800EA0D8 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3F66C 800EA0DC 03E00008 */  jr         $ra
    /* 3F670 800EA0E0 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800E9E34

nonmatching func_800EA0E4, 0xE4

glabel func_800EA0E4
    /* 3F674 800EA0E4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3F678 800EA0E8 AFB00010 */  sw         $s0, 0x10($sp)
    /* 3F67C 800EA0EC 00808021 */  addu       $s0, $a0, $zero
    /* 3F680 800EA0F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3F684 800EA0F4 8E02004C */  lw         $v0, 0x4C($s0)
    /* 3F688 800EA0F8 1040002F */  beqz       $v0, .L800EA1B8
    /* 3F68C 800EA0FC 00000000 */   nop
    /* 3F690 800EA100 0C03A8EF */  jal        func_800EA3BC
    /* 3F694 800EA104 00000000 */   nop
    /* 3F698 800EA108 8E020000 */  lw         $v0, 0x0($s0)
    /* 3F69C 800EA10C 2443FFFF */  addiu      $v1, $v0, -0x1
    /* 3F6A0 800EA110 2C620007 */  sltiu      $v0, $v1, 0x7
    /* 3F6A4 800EA114 10400027 */  beqz       $v0, .L800EA1B4
    /* 3F6A8 800EA118 00031080 */   sll       $v0, $v1, 2
    /* 3F6AC 800EA11C 3C01800F */  lui        $at, %hi(jtbl_800EB880)
    /* 3F6B0 800EA120 00220821 */  addu       $at, $at, $v0
    /* 3F6B4 800EA124 8C22B880 */  lw         $v0, %lo(jtbl_800EB880)($at)
    /* 3F6B8 800EA128 00400008 */  jr         $v0
    /* 3F6BC 800EA12C 00000000 */   nop
    /* 3F6C0 800EA130 8E020030 */  lw         $v0, 0x30($s0)
    /* 3F6C4 800EA134 10400003 */  beqz       $v0, .L800EA144
    /* 3F6C8 800EA138 00000000 */   nop
    /* 3F6CC 800EA13C 0C03A872 */  jal        func_800EA1C8
    /* 3F6D0 800EA140 02002021 */   addu      $a0, $s0, $zero
  .L800EA144:
    /* 3F6D4 800EA144 8E02002C */  lw         $v0, 0x2C($s0)
    /* 3F6D8 800EA148 5040001B */  beql       $v0, $zero, .L800EA1B8
    /* 3F6DC 800EA14C AE00004C */   sw        $zero, 0x4C($s0)
    /* 3F6E0 800EA150 0C03A8F9 */  jal        func_800EA3E4
    /* 3F6E4 800EA154 02002021 */   addu      $a0, $s0, $zero
    /* 3F6E8 800EA158 0803A86E */  j          .L800EA1B8
    /* 3F6EC 800EA15C AE00004C */   sw        $zero, 0x4C($s0)
    /* 3F6F0 800EA160 8E020030 */  lw         $v0, 0x30($s0)
    /* 3F6F4 800EA164 1040000E */  beqz       $v0, .L800EA1A0
    /* 3F6F8 800EA168 AE000018 */   sw        $zero, 0x18($s0)
    /* 3F6FC 800EA16C 0803A866 */  j          .L800EA198
    /* 3F700 800EA170 00000000 */   nop
    /* 3F704 800EA174 8E020030 */  lw         $v0, 0x30($s0)
    /* 3F708 800EA178 10400009 */  beqz       $v0, .L800EA1A0
    /* 3F70C 800EA17C AE000018 */   sw        $zero, 0x18($s0)
    /* 3F710 800EA180 0803A866 */  j          .L800EA198
    /* 3F714 800EA184 00000000 */   nop
    /* 3F718 800EA188 8E030030 */  lw         $v1, 0x30($s0)
    /* 3F71C 800EA18C 24020001 */  addiu      $v0, $zero, 0x1
    /* 3F720 800EA190 10600003 */  beqz       $v1, .L800EA1A0
    /* 3F724 800EA194 AE020018 */   sw        $v0, 0x18($s0)
  .L800EA198:
    /* 3F728 800EA198 0C03A872 */  jal        func_800EA1C8
    /* 3F72C 800EA19C 02002021 */   addu      $a0, $s0, $zero
  .L800EA1A0:
    /* 3F730 800EA1A0 8E02002C */  lw         $v0, 0x2C($s0)
    /* 3F734 800EA1A4 50400004 */  beql       $v0, $zero, .L800EA1B8
    /* 3F738 800EA1A8 AE00004C */   sw        $zero, 0x4C($s0)
    /* 3F73C 800EA1AC 0C03A95A */  jal        func_800EA568
    /* 3F740 800EA1B0 02002021 */   addu      $a0, $s0, $zero
  .L800EA1B4:
    /* 3F744 800EA1B4 AE00004C */  sw         $zero, 0x4C($s0)
  .L800EA1B8:
    /* 3F748 800EA1B8 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3F74C 800EA1BC 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3F750 800EA1C0 03E00008 */  jr         $ra
    /* 3F754 800EA1C4 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA0E4

nonmatching func_800EA1C8, 0x1F4

glabel func_800EA1C8
    /* 3F758 800EA1C8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3F75C 800EA1CC AFB00010 */  sw         $s0, 0x10($sp)
    /* 3F760 800EA1D0 00808021 */  addu       $s0, $a0, $zero
    /* 3F764 800EA1D4 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3F768 800EA1D8 8E020030 */  lw         $v0, 0x30($s0)
    /* 3F76C 800EA1DC 2443FFFF */  addiu      $v1, $v0, -0x1
    /* 3F770 800EA1E0 2C62000C */  sltiu      $v0, $v1, 0xC
    /* 3F774 800EA1E4 10400071 */  beqz       $v0, .L800EA3AC
    /* 3F778 800EA1E8 00031080 */   sll       $v0, $v1, 2
    /* 3F77C 800EA1EC 3C01800F */  lui        $at, %hi(jtbl_800EB8A0)
    /* 3F780 800EA1F0 00220821 */  addu       $at, $at, $v0
    /* 3F784 800EA1F4 8C22B8A0 */  lw         $v0, %lo(jtbl_800EB8A0)($at)
    /* 3F788 800EA1F8 00400008 */  jr         $v0
    /* 3F78C 800EA1FC 00000000 */   nop
    /* 3F790 800EA200 0C0206C2 */  jal        func_80081B08
    /* 3F794 800EA204 8E040024 */   lw        $a0, 0x24($s0)
    /* 3F798 800EA208 50400068 */  beql       $v0, $zero, .L800EA3AC
    /* 3F79C 800EA20C AE000020 */   sw        $zero, 0x20($s0)
    /* 3F7A0 800EA210 0803A8EB */  j          .L800EA3AC
    /* 3F7A4 800EA214 00000000 */   nop
    /* 3F7A8 800EA218 8E05003C */  lw         $a1, 0x3C($s0)
    /* 3F7AC 800EA21C 0C020531 */  jal        func_800814C4
    /* 3F7B0 800EA220 24040002 */   addiu     $a0, $zero, 0x2
    /* 3F7B4 800EA224 0803A8EB */  j          .L800EA3AC
    /* 3F7B8 800EA228 00000000 */   nop
    /* 3F7BC 800EA22C 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F7C0 800EA230 0C0206D8 */  jal        func_80081B60
    /* 3F7C4 800EA234 8E05003C */   lw        $a1, 0x3C($s0)
    /* 3F7C8 800EA238 0803A8EB */  j          .L800EA3AC
    /* 3F7CC 800EA23C 00000000 */   nop
    /* 3F7D0 800EA240 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F7D4 800EA244 00002821 */  addu       $a1, $zero, $zero
    /* 3F7D8 800EA248 AE00002C */  sw         $zero, 0x2C($s0)
    /* 3F7DC 800EA24C 0C020695 */  jal        func_80081A54
    /* 3F7E0 800EA250 AE000034 */   sw        $zero, 0x34($s0)
    /* 3F7E4 800EA254 0803A8EB */  j          .L800EA3AC
    /* 3F7E8 800EA258 00000000 */   nop
    /* 3F7EC 800EA25C 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F7F0 800EA260 8E05003C */  lw         $a1, 0x3C($s0)
    /* 3F7F4 800EA264 0C020695 */  jal        func_80081A54
    /* 3F7F8 800EA268 AE00002C */   sw        $zero, 0x2C($s0)
    /* 3F7FC 800EA26C 0803A8EB */  j          .L800EA3AC
    /* 3F800 800EA270 00000000 */   nop
    /* 3F804 800EA274 3C01800F */  lui        $at, %hi(D_800EB0DC)
    /* 3F808 800EA278 AC20B0DC */  sw         $zero, %lo(D_800EB0DC)($at)
    /* 3F80C 800EA27C 3C01800F */  lui        $at, %hi(D_800EB12C)
    /* 3F810 800EA280 AC20B12C */  sw         $zero, %lo(D_800EB12C)($at)
    /* 3F814 800EA284 3C01800F */  lui        $at, %hi(D_800EB17C)
    /* 3F818 800EA288 AC20B17C */  sw         $zero, %lo(D_800EB17C)($at)
    /* 3F81C 800EA28C 3C01800F */  lui        $at, %hi(D_800EB1CC)
    /* 3F820 800EA290 AC20B1CC */  sw         $zero, %lo(D_800EB1CC)($at)
    /* 3F824 800EA294 8E050034 */  lw         $a1, 0x34($s0)
    /* 3F828 800EA298 0C020642 */  jal        func_80081908
    /* 3F82C 800EA29C 24040002 */   addiu     $a0, $zero, 0x2
    /* 3F830 800EA2A0 0803A8EB */  j          .L800EA3AC
    /* 3F834 800EA2A4 00000000 */   nop
    /* 3F838 800EA2A8 3C01800F */  lui        $at, %hi(D_800EB21C)
    /* 3F83C 800EA2AC AC20B21C */  sw         $zero, %lo(D_800EB21C)($at)
    /* 3F840 800EA2B0 3C01800F */  lui        $at, %hi(D_800EB26C)
    /* 3F844 800EA2B4 AC20B26C */  sw         $zero, %lo(D_800EB26C)($at)
    /* 3F848 800EA2B8 3C01800F */  lui        $at, %hi(D_800EB2BC)
    /* 3F84C 800EA2BC AC20B2BC */  sw         $zero, %lo(D_800EB2BC)($at)
    /* 3F850 800EA2C0 8E050034 */  lw         $a1, 0x34($s0)
    /* 3F854 800EA2C4 0C020642 */  jal        func_80081908
    /* 3F858 800EA2C8 24040001 */   addiu     $a0, $zero, 0x1
    /* 3F85C 800EA2CC 0803A8EB */  j          .L800EA3AC
    /* 3F860 800EA2D0 00000000 */   nop
    /* 3F864 800EA2D4 3C01800F */  lui        $at, %hi(D_800EB0DC)
    /* 3F868 800EA2D8 AC20B0DC */  sw         $zero, %lo(D_800EB0DC)($at)
    /* 3F86C 800EA2DC 3C01800F */  lui        $at, %hi(D_800EB12C)
    /* 3F870 800EA2E0 AC20B12C */  sw         $zero, %lo(D_800EB12C)($at)
    /* 3F874 800EA2E4 3C01800F */  lui        $at, %hi(D_800EB17C)
    /* 3F878 800EA2E8 AC20B17C */  sw         $zero, %lo(D_800EB17C)($at)
    /* 3F87C 800EA2EC 3C01800F */  lui        $at, %hi(D_800EB1CC)
    /* 3F880 800EA2F0 AC20B1CC */  sw         $zero, %lo(D_800EB1CC)($at)
    /* 3F884 800EA2F4 3C01800F */  lui        $at, %hi(D_800EB21C)
    /* 3F888 800EA2F8 AC20B21C */  sw         $zero, %lo(D_800EB21C)($at)
    /* 3F88C 800EA2FC 3C01800F */  lui        $at, %hi(D_800EB26C)
    /* 3F890 800EA300 AC20B26C */  sw         $zero, %lo(D_800EB26C)($at)
    /* 3F894 800EA304 3C01800F */  lui        $at, %hi(D_800EB2BC)
    /* 3F898 800EA308 AC20B2BC */  sw         $zero, %lo(D_800EB2BC)($at)
    /* 3F89C 800EA30C 8E050034 */  lw         $a1, 0x34($s0)
    /* 3F8A0 800EA310 0C020642 */  jal        func_80081908
    /* 3F8A4 800EA314 24040003 */   addiu     $a0, $zero, 0x3
    /* 3F8A8 800EA318 0803A8EB */  j          .L800EA3AC
    /* 3F8AC 800EA31C 00000000 */   nop
    /* 3F8B0 800EA320 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F8B4 800EA324 0C0206F0 */  jal        func_80081BC0
    /* 3F8B8 800EA328 8E05003C */   lw        $a1, 0x3C($s0)
    /* 3F8BC 800EA32C 0803A8EB */  j          .L800EA3AC
    /* 3F8C0 800EA330 00000000 */   nop
    /* 3F8C4 800EA334 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F8C8 800EA338 0C02074B */  jal        func_80081D2C
    /* 3F8CC 800EA33C 8E050034 */   lw        $a1, 0x34($s0)
    /* 3F8D0 800EA340 8E020034 */  lw         $v0, 0x34($s0)
    /* 3F8D4 800EA344 0803A8EB */  j          .L800EA3AC
    /* 3F8D8 800EA348 AE020044 */   sw        $v0, 0x44($s0)
    /* 3F8DC 800EA34C 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F8E0 800EA350 0C020728 */  jal        func_80081CA0
    /* 3F8E4 800EA354 8E05003C */   lw        $a1, 0x3C($s0)
    /* 3F8E8 800EA358 0803A8EB */  j          .L800EA3AC
    /* 3F8EC 800EA35C 00000000 */   nop
    /* 3F8F0 800EA360 8E02003C */  lw         $v0, 0x3C($s0)
    /* 3F8F4 800EA364 44821000 */  mtc1       $v0, $fv1
    /* 3F8F8 800EA368 00000000 */  nop
    /* 3F8FC 800EA36C 04410004 */  bgez       $v0, .L800EA380
    /* 3F900 800EA370 468010A1 */   cvt.d.w   $fv1, $fv1
    /* 3F904 800EA374 3C01800F */  lui        $at, %hi(D_800EB8D0)
    /* 3F908 800EA378 D420B8D0 */  ldc1       $fv0, %lo(D_800EB8D0)($at)
    /* 3F90C 800EA37C 46201080 */  add.d      $fv1, $fv1, $fv0
  .L800EA380:
    /* 3F910 800EA380 3C01800F */  lui        $at, %hi(D_800EB8D8)
    /* 3F914 800EA384 D420B8D8 */  ldc1       $fv0, %lo(D_800EB8D8)($at)
    /* 3F918 800EA388 46201003 */  div.d      $fv0, $fv1, $fv0
    /* 3F91C 800EA38C 3C01800F */  lui        $at, %hi(D_800EB8E0)
    /* 3F920 800EA390 D422B8E0 */  ldc1       $fv1, %lo(D_800EB8E0)($at)
    /* 3F924 800EA394 46220001 */  sub.d      $fv0, $fv0, $fv1
    /* 3F928 800EA398 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F92C 800EA39C 46200020 */  cvt.s.d    $fv0, $fv0
    /* 3F930 800EA3A0 44050000 */  mfc1       $a1, $fv0
    /* 3F934 800EA3A4 0C02070C */  jal        func_80081C30
    /* 3F938 800EA3A8 00000000 */   nop
  .L800EA3AC:
    /* 3F93C 800EA3AC 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3F940 800EA3B0 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3F944 800EA3B4 03E00008 */  jr         $ra
    /* 3F948 800EA3B8 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA1C8

nonmatching func_800EA3BC, 0x28

glabel func_800EA3BC
    /* 3F94C 800EA3BC 8C820004 */  lw         $v0, 0x4($a0)
    /* 3F950 800EA3C0 8C830008 */  lw         $v1, 0x8($a0)
    /* 3F954 800EA3C4 8C85000C */  lw         $a1, 0xC($a0)
    /* 3F958 800EA3C8 AC800004 */  sw         $zero, 0x4($a0)
    /* 3F95C 800EA3CC AC800008 */  sw         $zero, 0x8($a0)
    /* 3F960 800EA3D0 AC80000C */  sw         $zero, 0xC($a0)
    /* 3F964 800EA3D4 AC82002C */  sw         $v0, 0x2C($a0)
    /* 3F968 800EA3D8 AC830030 */  sw         $v1, 0x30($a0)
    /* 3F96C 800EA3DC 03E00008 */  jr         $ra
    /* 3F970 800EA3E0 AC850034 */   sw        $a1, 0x34($a0)
endlabel func_800EA3BC

nonmatching func_800EA3E4, 0xA4

glabel func_800EA3E4
    /* 3F974 800EA3E4 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3F978 800EA3E8 AFB00010 */  sw         $s0, 0x10($sp)
    /* 3F97C 800EA3EC 00808021 */  addu       $s0, $a0, $zero
    /* 3F980 800EA3F0 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3F984 800EA3F4 0C0206C2 */  jal        func_80081B08
    /* 3F988 800EA3F8 8E040024 */   lw        $a0, 0x24($s0)
    /* 3F98C 800EA3FC 14400007 */  bnez       $v0, .L800EA41C
    /* 3F990 800EA400 00000000 */   nop
    /* 3F994 800EA404 3C01800F */  lui        $at, %hi(D_800EB0E8)
    /* 3F998 800EA408 AC20B0E8 */  sw         $zero, %lo(D_800EB0E8)($at)
    /* 3F99C 800EA40C 0C03A922 */  jal        func_800EA488
    /* 3F9A0 800EA410 02002021 */   addu      $a0, $s0, $zero
    /* 3F9A4 800EA414 0803A91E */  j          .L800EA478
    /* 3F9A8 800EA418 00000000 */   nop
  .L800EA41C:
    /* 3F9AC 800EA41C 8E020038 */  lw         $v0, 0x38($s0)
    /* 3F9B0 800EA420 14400013 */  bnez       $v0, .L800EA470
    /* 3F9B4 800EA424 00000000 */   nop
    /* 3F9B8 800EA428 8E050034 */  lw         $a1, 0x34($s0)
    /* 3F9BC 800EA42C 10A00006 */  beqz       $a1, .L800EA448
    /* 3F9C0 800EA430 00000000 */   nop
    /* 3F9C4 800EA434 0C020695 */  jal        func_80081A54
    /* 3F9C8 800EA438 8E040024 */   lw        $a0, 0x24($s0)
    /* 3F9CC 800EA43C 8E020034 */  lw         $v0, 0x34($s0)
    /* 3F9D0 800EA440 0803A916 */  j          .L800EA458
    /* 3F9D4 800EA444 24420003 */   addiu     $v0, $v0, 0x3
  .L800EA448:
    /* 3F9D8 800EA448 8E040024 */  lw         $a0, 0x24($s0)
    /* 3F9DC 800EA44C 0C020695 */  jal        func_80081A54
    /* 3F9E0 800EA450 24050001 */   addiu     $a1, $zero, 0x1
    /* 3F9E4 800EA454 24020003 */  addiu      $v0, $zero, 0x3
  .L800EA458:
    /* 3F9E8 800EA458 AE02003C */  sw         $v0, 0x3C($s0)
    /* 3F9EC 800EA45C 8E03002C */  lw         $v1, 0x2C($s0)
    /* 3F9F0 800EA460 24020002 */  addiu      $v0, $zero, 0x2
    /* 3F9F4 800EA464 AE020038 */  sw         $v0, 0x38($s0)
    /* 3F9F8 800EA468 0803A91E */  j          .L800EA478
    /* 3F9FC 800EA46C AE030040 */   sw        $v1, 0x40($s0)
  .L800EA470:
    /* 3FA00 800EA470 8E02002C */  lw         $v0, 0x2C($s0)
    /* 3FA04 800EA474 AE020040 */  sw         $v0, 0x40($s0)
  .L800EA478:
    /* 3FA08 800EA478 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3FA0C 800EA47C 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FA10 800EA480 03E00008 */  jr         $ra
    /* 3FA14 800EA484 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA3E4

nonmatching func_800EA488, 0xE0

glabel func_800EA488
    /* 3FA18 800EA488 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3FA1C 800EA48C AFB10014 */  sw         $s1, 0x14($sp)
    /* 3FA20 800EA490 00808821 */  addu       $s1, $a0, $zero
    /* 3FA24 800EA494 AFBF001C */  sw         $ra, 0x1C($sp)
    /* 3FA28 800EA498 AFB20018 */  sw         $s2, 0x18($sp)
    /* 3FA2C 800EA49C AFB00010 */  sw         $s0, 0x10($sp)
    /* 3FA30 800EA4A0 8E22002C */  lw         $v0, 0x2C($s1)
    /* 3FA34 800EA4A4 8E240024 */  lw         $a0, 0x24($s1)
    /* 3FA38 800EA4A8 0C0206C2 */  jal        func_80081B08
    /* 3FA3C 800EA4AC 2452FFFF */   addiu     $s2, $v0, -0x1
    /* 3FA40 800EA4B0 10400005 */  beqz       $v0, .L800EA4C8
    /* 3FA44 800EA4B4 001280C0 */   sll       $s0, $s2, 3
    /* 3FA48 800EA4B8 8E240024 */  lw         $a0, 0x24($s1)
    /* 3FA4C 800EA4BC 0C020695 */  jal        func_80081A54
    /* 3FA50 800EA4C0 00002821 */   addu      $a1, $zero, $zero
    /* 3FA54 800EA4C4 001280C0 */  sll        $s0, $s2, 3
  .L800EA4C8:
    /* 3FA58 800EA4C8 3C04800F */  lui        $a0, %hi(D_800EB4F0)
    /* 3FA5C 800EA4CC 00902021 */  addu       $a0, $a0, $s0
    /* 3FA60 800EA4D0 8C84B4F0 */  lw         $a0, %lo(D_800EB4F0)($a0)
    /* 3FA64 800EA4D4 3C06800F */  lui        $a2, %hi(D_800EB4F4)
    /* 3FA68 800EA4D8 00D03021 */  addu       $a2, $a2, $s0
    /* 3FA6C 800EA4DC 8CC6B4F4 */  lw         $a2, %lo(D_800EB4F4)($a2)
    /* 3FA70 800EA4E0 8E250048 */  lw         $a1, 0x48($s1)
    /* 3FA74 800EA4E4 00C43023 */  subu       $a2, $a2, $a0
    /* 3FA78 800EA4E8 0C0227E0 */  jal        func_80089F80
    /* 3FA7C 800EA4EC 24C60004 */   addiu     $a2, $a2, 0x4
    /* 3FA80 800EA4F0 3C05800F */  lui        $a1, %hi(D_800EB2E0)
    /* 3FA84 800EA4F4 00B02821 */  addu       $a1, $a1, $s0
    /* 3FA88 800EA4F8 8CA5B2E0 */  lw         $a1, %lo(D_800EB2E0)($a1)
    /* 3FA8C 800EA4FC 0C020531 */  jal        func_800814C4
    /* 3FA90 800EA500 24040002 */   addiu     $a0, $zero, 0x2
    /* 3FA94 800EA504 26230024 */  addiu      $v1, $s1, 0x24
    /* 3FA98 800EA508 3C02800F */  lui        $v0, %hi(D_800EB174)
    /* 3FA9C 800EA50C 2442B174 */  addiu      $v0, $v0, %lo(D_800EB174)
    /* 3FAA0 800EA510 14620004 */  bne        $v1, $v0, .L800EA524
    /* 3FAA4 800EA514 00000000 */   nop
    /* 3FAA8 800EA518 3C048010 */  lui        $a0, %hi(D_80104710)
    /* 3FAAC 800EA51C 0C02077C */  jal        func_80081DF0
    /* 3FAB0 800EA520 24844710 */   addiu     $a0, $a0, %lo(D_80104710)
  .L800EA524:
    /* 3FAB4 800EA524 0C02053C */  jal        func_800814F0
    /* 3FAB8 800EA528 8E240048 */   lw        $a0, 0x48($s1)
    /* 3FABC 800EA52C AE220024 */  sw         $v0, 0x24($s1)
    /* 3FAC0 800EA530 8E240024 */  lw         $a0, 0x24($s1)
    /* 3FAC4 800EA534 001210C0 */  sll        $v0, $s2, 3
    /* 3FAC8 800EA538 3C05800F */  lui        $a1, %hi(D_800EB2E4)
    /* 3FACC 800EA53C 00A22821 */  addu       $a1, $a1, $v0
    /* 3FAD0 800EA540 0C02074B */  jal        func_80081D2C
    /* 3FAD4 800EA544 8CA5B2E4 */   lw        $a1, %lo(D_800EB2E4)($a1)
    /* 3FAD8 800EA548 8E22002C */  lw         $v0, 0x2C($s1)
    /* 3FADC 800EA54C AE220020 */  sw         $v0, 0x20($s1)
    /* 3FAE0 800EA550 8FBF001C */  lw         $ra, 0x1C($sp)
    /* 3FAE4 800EA554 8FB20018 */  lw         $s2, 0x18($sp)
    /* 3FAE8 800EA558 8FB10014 */  lw         $s1, 0x14($sp)
    /* 3FAEC 800EA55C 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FAF0 800EA560 03E00008 */  jr         $ra
    /* 3FAF4 800EA564 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800EA488

nonmatching func_800EA568, 0x9C

glabel func_800EA568
    /* 3FAF8 800EA568 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FAFC 800EA56C AFB00010 */  sw         $s0, 0x10($sp)
    /* 3FB00 800EA570 00808021 */  addu       $s0, $a0, $zero
    /* 3FB04 800EA574 AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3FB08 800EA578 8E020018 */  lw         $v0, 0x18($s0)
    /* 3FB0C 800EA57C 10400008 */  beqz       $v0, .L800EA5A0
    /* 3FB10 800EA580 2402FFFF */   addiu     $v0, $zero, -0x1
    /* 3FB14 800EA584 8E040024 */  lw         $a0, 0x24($s0)
    /* 3FB18 800EA588 0C0206C2 */  jal        func_80081B08
    /* 3FB1C 800EA58C 00000000 */   nop
    /* 3FB20 800EA590 1040000D */  beqz       $v0, .L800EA5C8
    /* 3FB24 800EA594 00000000 */   nop
    /* 3FB28 800EA598 0803A970 */  j          .L800EA5C0
    /* 3FB2C 800EA59C 8E040024 */   lw        $a0, 0x24($s0)
  .L800EA5A0:
    /* 3FB30 800EA5A0 8E040028 */  lw         $a0, 0x28($s0)
    /* 3FB34 800EA5A4 10820008 */  beq        $a0, $v0, .L800EA5C8
    /* 3FB38 800EA5A8 00000000 */   nop
    /* 3FB3C 800EA5AC 0C0206C2 */  jal        func_80081B08
    /* 3FB40 800EA5B0 00000000 */   nop
    /* 3FB44 800EA5B4 10400004 */  beqz       $v0, .L800EA5C8
    /* 3FB48 800EA5B8 00000000 */   nop
    /* 3FB4C 800EA5BC 8E040028 */  lw         $a0, 0x28($s0)
  .L800EA5C0:
    /* 3FB50 800EA5C0 0C020695 */  jal        func_80081A54
    /* 3FB54 800EA5C4 00002821 */   addu      $a1, $zero, $zero
  .L800EA5C8:
    /* 3FB58 800EA5C8 8E020024 */  lw         $v0, 0x24($s0)
    /* 3FB5C 800EA5CC 3C048010 */  lui        $a0, %hi(D_80104710)
    /* 3FB60 800EA5D0 24844710 */  addiu      $a0, $a0, %lo(D_80104710)
    /* 3FB64 800EA5D4 0C02077C */  jal        func_80081DF0
    /* 3FB68 800EA5D8 AE020028 */   sw        $v0, 0x28($s0)
    /* 3FB6C 800EA5DC 8E04002C */  lw         $a0, 0x2C($s0)
    /* 3FB70 800EA5E0 0C0205DC */  jal        func_80081770
    /* 3FB74 800EA5E4 2484FFFF */   addiu     $a0, $a0, -0x1
    /* 3FB78 800EA5E8 8E03002C */  lw         $v1, 0x2C($s0)
    /* 3FB7C 800EA5EC AE020024 */  sw         $v0, 0x24($s0)
    /* 3FB80 800EA5F0 AE030020 */  sw         $v1, 0x20($s0)
    /* 3FB84 800EA5F4 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3FB88 800EA5F8 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FB8C 800EA5FC 03E00008 */  jr         $ra
    /* 3FB90 800EA600 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA568

nonmatching func_800EA604, 0xAC

glabel func_800EA604
    /* 3FB94 800EA604 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3FB98 800EA608 AFB00010 */  sw         $s0, 0x10($sp)
    /* 3FB9C 800EA60C 00808021 */  addu       $s0, $a0, $zero
    /* 3FBA0 800EA610 AFB10014 */  sw         $s1, 0x14($sp)
    /* 3FBA4 800EA614 00A08821 */  addu       $s1, $a1, $zero
    /* 3FBA8 800EA618 3C02800F */  lui        $v0, %hi(D_800EB1F0)
    /* 3FBAC 800EA61C 2442B1F0 */  addiu      $v0, $v0, %lo(D_800EB1F0)
    /* 3FBB0 800EA620 12020012 */  beq        $s0, $v0, .L800EA66C
    /* 3FBB4 800EA624 AFBF0018 */   sw        $ra, 0x18($sp)
    /* 3FBB8 800EA628 3C02800F */  lui        $v0, %hi(D_800EB240)
    /* 3FBBC 800EA62C 2442B240 */  addiu      $v0, $v0, %lo(D_800EB240)
    /* 3FBC0 800EA630 02021026 */  xor        $v0, $s0, $v0
    /* 3FBC4 800EA634 2C420001 */  sltiu      $v0, $v0, 0x1
    /* 3FBC8 800EA638 2E030001 */  sltiu      $v1, $s0, 0x1
    /* 3FBCC 800EA63C 00431025 */  or         $v0, $v0, $v1
    /* 3FBD0 800EA640 5440000B */  bnel       $v0, $zero, .L800EA670
    /* 3FBD4 800EA644 02002021 */   addu      $a0, $s0, $zero
    /* 3FBD8 800EA648 3C02800F */  lui        $v0, %hi(D_800EB290)
    /* 3FBDC 800EA64C 2442B290 */  addiu      $v0, $v0, %lo(D_800EB290)
    /* 3FBE0 800EA650 1602000D */  bne        $s0, $v0, .L800EA688
    /* 3FBE4 800EA654 26220001 */   addiu     $v0, $s1, 0x1
    /* 3FBE8 800EA658 02002021 */  addu       $a0, $s0, $zero
    /* 3FBEC 800EA65C 24050002 */  addiu      $a1, $zero, 0x2
    /* 3FBF0 800EA660 00003021 */  addu       $a2, $zero, $zero
    /* 3FBF4 800EA664 0C03AA49 */  jal        func_800EA924
    /* 3FBF8 800EA668 24074000 */   addiu     $a3, $zero, 0x4000
  .L800EA66C:
    /* 3FBFC 800EA66C 02002021 */  addu       $a0, $s0, $zero
  .L800EA670:
    /* 3FC00 800EA670 24050001 */  addiu      $a1, $zero, 0x1
    /* 3FC04 800EA674 3226FFFF */  andi       $a2, $s1, 0xFFFF
    /* 3FC08 800EA678 0C03AA49 */  jal        func_800EA924
    /* 3FC0C 800EA67C 24074000 */   addiu     $a3, $zero, 0x4000
    /* 3FC10 800EA680 0803A9A7 */  j          .L800EA69C
    /* 3FC14 800EA684 00000000 */   nop
  .L800EA688:
    /* 3FC18 800EA688 AE020004 */  sw         $v0, 0x4($s0)
    /* 3FC1C 800EA68C 24020004 */  addiu      $v0, $zero, 0x4
    /* 3FC20 800EA690 AE02000C */  sw         $v0, 0xC($s0)
    /* 3FC24 800EA694 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FC28 800EA698 AE02004C */  sw         $v0, 0x4C($s0)
  .L800EA69C:
    /* 3FC2C 800EA69C 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 3FC30 800EA6A0 8FB10014 */  lw         $s1, 0x14($sp)
    /* 3FC34 800EA6A4 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FC38 800EA6A8 03E00008 */  jr         $ra
    /* 3FC3C 800EA6AC 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800EA604

nonmatching func_800EA6B0, 0x18

glabel func_800EA6B0
    /* 3FC40 800EA6B0 24A50001 */  addiu      $a1, $a1, 0x1
    /* 3FC44 800EA6B4 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FC48 800EA6B8 AC850004 */  sw         $a1, 0x4($a0)
    /* 3FC4C 800EA6BC AC86000C */  sw         $a2, 0xC($a0)
    /* 3FC50 800EA6C0 03E00008 */  jr         $ra
    /* 3FC54 800EA6C4 AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA6B0

nonmatching func_800EA6C8, 0x4C

glabel func_800EA6C8
    /* 3FC58 800EA6C8 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FC5C 800EA6CC AFB00010 */  sw         $s0, 0x10($sp)
    /* 3FC60 800EA6D0 00808021 */  addu       $s0, $a0, $zero
    /* 3FC64 800EA6D4 24050002 */  addiu      $a1, $zero, 0x2
    /* 3FC68 800EA6D8 00003021 */  addu       $a2, $zero, $zero
    /* 3FC6C 800EA6DC AFBF0014 */  sw         $ra, 0x14($sp)
    /* 3FC70 800EA6E0 0C03AA49 */  jal        func_800EA924
    /* 3FC74 800EA6E4 24074000 */   addiu     $a3, $zero, 0x4000
    /* 3FC78 800EA6E8 14400006 */  bnez       $v0, .L800EA704
    /* 3FC7C 800EA6EC 24020005 */   addiu     $v0, $zero, 0x5
    /* 3FC80 800EA6F0 AE020008 */  sw         $v0, 0x8($s0)
    /* 3FC84 800EA6F4 24020004 */  addiu      $v0, $zero, 0x4
    /* 3FC88 800EA6F8 AE02003C */  sw         $v0, 0x3C($s0)
    /* 3FC8C 800EA6FC 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FC90 800EA700 AE02004C */  sw         $v0, 0x4C($s0)
  .L800EA704:
    /* 3FC94 800EA704 8FBF0014 */  lw         $ra, 0x14($sp)
    /* 3FC98 800EA708 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FC9C 800EA70C 03E00008 */  jr         $ra
    /* 3FCA0 800EA710 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA6C8

nonmatching func_800EA714, 0x58

glabel func_800EA714
    /* 3FCA4 800EA714 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FCA8 800EA718 24040003 */  addiu      $a0, $zero, 0x3
    /* 3FCAC 800EA71C AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3FCB0 800EA720 3C01800F */  lui        $at, %hi(D_800EB0DC)
    /* 3FCB4 800EA724 AC20B0DC */  sw         $zero, %lo(D_800EB0DC)($at)
    /* 3FCB8 800EA728 3C01800F */  lui        $at, %hi(D_800EB12C)
    /* 3FCBC 800EA72C AC20B12C */  sw         $zero, %lo(D_800EB12C)($at)
    /* 3FCC0 800EA730 3C01800F */  lui        $at, %hi(D_800EB17C)
    /* 3FCC4 800EA734 AC20B17C */  sw         $zero, %lo(D_800EB17C)($at)
    /* 3FCC8 800EA738 3C01800F */  lui        $at, %hi(D_800EB1CC)
    /* 3FCCC 800EA73C AC20B1CC */  sw         $zero, %lo(D_800EB1CC)($at)
    /* 3FCD0 800EA740 3C01800F */  lui        $at, %hi(D_800EB21C)
    /* 3FCD4 800EA744 AC20B21C */  sw         $zero, %lo(D_800EB21C)($at)
    /* 3FCD8 800EA748 3C01800F */  lui        $at, %hi(D_800EB26C)
    /* 3FCDC 800EA74C AC20B26C */  sw         $zero, %lo(D_800EB26C)($at)
    /* 3FCE0 800EA750 3C01800F */  lui        $at, %hi(D_800EB2BC)
    /* 3FCE4 800EA754 AC20B2BC */  sw         $zero, %lo(D_800EB2BC)($at)
    /* 3FCE8 800EA758 0C020642 */  jal        func_80081908
    /* 3FCEC 800EA75C 00002821 */   addu      $a1, $zero, $zero
    /* 3FCF0 800EA760 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3FCF4 800EA764 03E00008 */  jr         $ra
    /* 3FCF8 800EA768 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA714

nonmatching func_800EA76C, 0x40

glabel func_800EA76C
    /* 3FCFC 800EA76C 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FD00 800EA770 24040002 */  addiu      $a0, $zero, 0x2
    /* 3FD04 800EA774 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3FD08 800EA778 3C01800F */  lui        $at, %hi(D_800EB0DC)
    /* 3FD0C 800EA77C AC20B0DC */  sw         $zero, %lo(D_800EB0DC)($at)
    /* 3FD10 800EA780 3C01800F */  lui        $at, %hi(D_800EB12C)
    /* 3FD14 800EA784 AC20B12C */  sw         $zero, %lo(D_800EB12C)($at)
    /* 3FD18 800EA788 3C01800F */  lui        $at, %hi(D_800EB17C)
    /* 3FD1C 800EA78C AC20B17C */  sw         $zero, %lo(D_800EB17C)($at)
    /* 3FD20 800EA790 3C01800F */  lui        $at, %hi(D_800EB1CC)
    /* 3FD24 800EA794 AC20B1CC */  sw         $zero, %lo(D_800EB1CC)($at)
    /* 3FD28 800EA798 0C020642 */  jal        func_80081908
    /* 3FD2C 800EA79C 00002821 */   addu      $a1, $zero, $zero
    /* 3FD30 800EA7A0 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3FD34 800EA7A4 03E00008 */  jr         $ra
    /* 3FD38 800EA7A8 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA76C

nonmatching func_800EA7AC, 0x38

glabel func_800EA7AC
    /* 3FD3C 800EA7AC 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FD40 800EA7B0 24040001 */  addiu      $a0, $zero, 0x1
    /* 3FD44 800EA7B4 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3FD48 800EA7B8 3C01800F */  lui        $at, %hi(D_800EB21C)
    /* 3FD4C 800EA7BC AC20B21C */  sw         $zero, %lo(D_800EB21C)($at)
    /* 3FD50 800EA7C0 3C01800F */  lui        $at, %hi(D_800EB26C)
    /* 3FD54 800EA7C4 AC20B26C */  sw         $zero, %lo(D_800EB26C)($at)
    /* 3FD58 800EA7C8 3C01800F */  lui        $at, %hi(D_800EB2BC)
    /* 3FD5C 800EA7CC AC20B2BC */  sw         $zero, %lo(D_800EB2BC)($at)
    /* 3FD60 800EA7D0 0C020642 */  jal        func_80081908
    /* 3FD64 800EA7D4 00002821 */   addu      $a1, $zero, $zero
    /* 3FD68 800EA7D8 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3FD6C 800EA7DC 03E00008 */  jr         $ra
    /* 3FD70 800EA7E0 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA7AC

nonmatching func_800EA7E4, 0x54

glabel func_800EA7E4
    /* 3FD74 800EA7E4 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3FD78 800EA7E8 AFB00010 */  sw         $s0, 0x10($sp)
    /* 3FD7C 800EA7EC 00808021 */  addu       $s0, $a0, $zero
    /* 3FD80 800EA7F0 AFB10014 */  sw         $s1, 0x14($sp)
    /* 3FD84 800EA7F4 00A08821 */  addu       $s1, $a1, $zero
    /* 3FD88 800EA7F8 24050002 */  addiu      $a1, $zero, 0x2
    /* 3FD8C 800EA7FC 3226FFFF */  andi       $a2, $s1, 0xFFFF
    /* 3FD90 800EA800 AFBF0018 */  sw         $ra, 0x18($sp)
    /* 3FD94 800EA804 0C03AA49 */  jal        func_800EA924
    /* 3FD98 800EA808 24074000 */   addiu     $a3, $zero, 0x4000
    /* 3FD9C 800EA80C 14400005 */  bnez       $v0, .L800EA824
    /* 3FDA0 800EA810 24020005 */   addiu     $v0, $zero, 0x5
    /* 3FDA4 800EA814 AE020008 */  sw         $v0, 0x8($s0)
    /* 3FDA8 800EA818 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FDAC 800EA81C AE11003C */  sw         $s1, 0x3C($s0)
    /* 3FDB0 800EA820 AE02004C */  sw         $v0, 0x4C($s0)
  .L800EA824:
    /* 3FDB4 800EA824 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 3FDB8 800EA828 8FB10014 */  lw         $s1, 0x14($sp)
    /* 3FDBC 800EA82C 8FB00010 */  lw         $s0, 0x10($sp)
    /* 3FDC0 800EA830 03E00008 */  jr         $ra
    /* 3FDC4 800EA834 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800EA7E4

nonmatching func_800EA838, 0x18

glabel func_800EA838
    /* 3FDC8 800EA838 24020002 */  addiu      $v0, $zero, 0x2
    /* 3FDCC 800EA83C AC820008 */  sw         $v0, 0x8($a0)
    /* 3FDD0 800EA840 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FDD4 800EA844 AC85003C */  sw         $a1, 0x3C($a0)
    /* 3FDD8 800EA848 03E00008 */  jr         $ra
    /* 3FDDC 800EA84C AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA838

nonmatching func_800EA850, 0x1C

glabel func_800EA850
    /* 3FDE0 800EA850 27BDFFE8 */  addiu      $sp, $sp, -0x18
    /* 3FDE4 800EA854 AFBF0010 */  sw         $ra, 0x10($sp)
    /* 3FDE8 800EA858 0C0206C2 */  jal        func_80081B08
    /* 3FDEC 800EA85C 8C840024 */   lw        $a0, 0x24($a0)
    /* 3FDF0 800EA860 8FBF0010 */  lw         $ra, 0x10($sp)
    /* 3FDF4 800EA864 03E00008 */  jr         $ra
    /* 3FDF8 800EA868 27BD0018 */   addiu     $sp, $sp, 0x18
endlabel func_800EA850

nonmatching func_800EA86C, 0x18

glabel func_800EA86C
    /* 3FDFC 800EA86C 2402000B */  addiu      $v0, $zero, 0xB
    /* 3FE00 800EA870 AC820008 */  sw         $v0, 0x8($a0)
    /* 3FE04 800EA874 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FE08 800EA878 AC85003C */  sw         $a1, 0x3C($a0)
    /* 3FE0C 800EA87C 03E00008 */  jr         $ra
    /* 3FE10 800EA880 AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA86C

nonmatching func_800EA884, 0x18

glabel func_800EA884
    /* 3FE14 800EA884 24020003 */  addiu      $v0, $zero, 0x3
    /* 3FE18 800EA888 AC820008 */  sw         $v0, 0x8($a0)
    /* 3FE1C 800EA88C 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FE20 800EA890 AC85003C */  sw         $a1, 0x3C($a0)
    /* 3FE24 800EA894 03E00008 */  jr         $ra
    /* 3FE28 800EA898 AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA884

nonmatching func_800EA89C, 0x18

glabel func_800EA89C
    /* 3FE2C 800EA89C 24020009 */  addiu      $v0, $zero, 0x9
    /* 3FE30 800EA8A0 AC820008 */  sw         $v0, 0x8($a0)
    /* 3FE34 800EA8A4 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FE38 800EA8A8 AC85003C */  sw         $a1, 0x3C($a0)
    /* 3FE3C 800EA8AC 03E00008 */  jr         $ra
    /* 3FE40 800EA8B0 AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA89C

nonmatching func_800EA8B4, 0x18

glabel func_800EA8B4
    /* 3FE44 800EA8B4 2402000C */  addiu      $v0, $zero, 0xC
    /* 3FE48 800EA8B8 AC820008 */  sw         $v0, 0x8($a0)
    /* 3FE4C 800EA8BC 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FE50 800EA8C0 AC85003C */  sw         $a1, 0x3C($a0)
    /* 3FE54 800EA8C4 03E00008 */  jr         $ra
    /* 3FE58 800EA8C8 AC82004C */   sw        $v0, 0x4C($a0)
endlabel func_800EA8B4

nonmatching func_800EA8CC, 0xC

glabel func_800EA8CC
    /* 3FE5C 800EA8CC 3C018016 */  lui        $at, %hi(D_80164760)
    /* 3FE60 800EA8D0 03E00008 */  jr         $ra
    /* 3FE64 800EA8D4 AC244760 */   sw        $a0, %lo(D_80164760)($at)
endlabel func_800EA8CC
    /* 3FE68 800EA8D8 00000000 */  nop
    /* 3FE6C 800EA8DC 00000000 */  nop

nonmatching func_800EA8E0, 0x44

glabel func_800EA8E0
    /* 3FE70 800EA8E0 24020078 */  addiu      $v0, $zero, 0x78
  .L800EA8E4:
    /* 3FE74 800EA8E4 3C01800F */  lui        $at, %hi(D_800EB8F0)
    /* 3FE78 800EA8E8 00220821 */  addu       $at, $at, $v0
    /* 3FE7C 800EA8EC A020B8F0 */  sb         $zero, %lo(D_800EB8F0)($at)
    /* 3FE80 800EA8F0 2442FFF8 */  addiu      $v0, $v0, -0x8
    /* 3FE84 800EA8F4 0441FFFB */  bgez       $v0, .L800EA8E4
    /* 3FE88 800EA8F8 00000000 */   nop
    /* 3FE8C 800EA8FC 24020078 */  addiu      $v0, $zero, 0x78
  .L800EA900:
    /* 3FE90 800EA900 3C01800F */  lui        $at, %hi(D_800EB970)
    /* 3FE94 800EA904 00220821 */  addu       $at, $at, $v0
    /* 3FE98 800EA908 A020B970 */  sb         $zero, %lo(D_800EB970)($at)
    /* 3FE9C 800EA90C 2442FFF8 */  addiu      $v0, $v0, -0x8
    /* 3FEA0 800EA910 0441FFFB */  bgez       $v0, .L800EA900
    /* 3FEA4 800EA914 00000000 */   nop
    /* 3FEA8 800EA918 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 3FEAC 800EA91C 03E00008 */  jr         $ra
    /* 3FEB0 800EA920 AC20BAF0 */   sw        $zero, %lo(D_800EBAF0)($at)
endlabel func_800EA8E0

nonmatching func_800EA924, 0x98

glabel func_800EA924
    /* 3FEB4 800EA924 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3FEB8 800EA928 3C02800F */  lui        $v0, %hi(D_800EB1F0)
    /* 3FEBC 800EA92C 2442B1F0 */  addiu      $v0, $v0, %lo(D_800EB1F0)
    /* 3FEC0 800EA930 14820005 */  bne        $a0, $v0, .L800EA948
    /* 3FEC4 800EA934 AFBF0018 */   sw        $ra, 0x18($sp)
    /* 3FEC8 800EA938 AFA00010 */  sw         $zero, 0x10($sp)
    /* 3FECC 800EA93C 30A400FF */  andi       $a0, $a1, 0xFF
    /* 3FED0 800EA940 0803AA68 */  j          .L800EA9A0
    /* 3FED4 800EA944 24050004 */   addiu     $a1, $zero, 0x4
  .L800EA948:
    /* 3FED8 800EA948 3C02800F */  lui        $v0, %hi(D_800EB240)
    /* 3FEDC 800EA94C 2442B240 */  addiu      $v0, $v0, %lo(D_800EB240)
    /* 3FEE0 800EA950 14820005 */  bne        $a0, $v0, .L800EA968
    /* 3FEE4 800EA954 00000000 */   nop
    /* 3FEE8 800EA958 AFA00010 */  sw         $zero, 0x10($sp)
    /* 3FEEC 800EA95C 30A400FF */  andi       $a0, $a1, 0xFF
    /* 3FEF0 800EA960 0803AA68 */  j          .L800EA9A0
    /* 3FEF4 800EA964 24050005 */   addiu     $a1, $zero, 0x5
  .L800EA968:
    /* 3FEF8 800EA968 3C02800F */  lui        $v0, %hi(D_800EB290)
    /* 3FEFC 800EA96C 2442B290 */  addiu      $v0, $v0, %lo(D_800EB290)
    /* 3FF00 800EA970 14820005 */  bne        $a0, $v0, .L800EA988
    /* 3FF04 800EA974 24020002 */   addiu     $v0, $zero, 0x2
    /* 3FF08 800EA978 AFA20010 */  sw         $v0, 0x10($sp)
    /* 3FF0C 800EA97C 30A400FF */  andi       $a0, $a1, 0xFF
    /* 3FF10 800EA980 0803AA68 */  j          .L800EA9A0
    /* 3FF14 800EA984 24050006 */   addiu     $a1, $zero, 0x6
  .L800EA988:
    /* 3FF18 800EA988 14800009 */  bnez       $a0, .L800EA9B0
    /* 3FF1C 800EA98C 00001021 */   addu      $v0, $zero, $zero
    /* 3FF20 800EA990 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FF24 800EA994 AFA20010 */  sw         $v0, 0x10($sp)
    /* 3FF28 800EA998 30A400FF */  andi       $a0, $a1, 0xFF
    /* 3FF2C 800EA99C 24050007 */  addiu      $a1, $zero, 0x7
  .L800EA9A0:
    /* 3FF30 800EA9A0 30C6FFFF */  andi       $a2, $a2, 0xFFFF
    /* 3FF34 800EA9A4 0C03AA6F */  jal        func_800EA9BC
    /* 3FF38 800EA9A8 30E7FFFF */   andi      $a3, $a3, 0xFFFF
    /* 3FF3C 800EA9AC 24020001 */  addiu      $v0, $zero, 0x1
  .L800EA9B0:
    /* 3FF40 800EA9B0 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 3FF44 800EA9B4 03E00008 */  jr         $ra
    /* 3FF48 800EA9B8 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800EA924

nonmatching func_800EA9BC, 0x184

glabel func_800EA9BC
    /* 3FF4C 800EA9BC 27BDFFE0 */  addiu      $sp, $sp, -0x20
    /* 3FF50 800EA9C0 8FA80030 */  lw         $t0, 0x30($sp)
    /* 3FF54 800EA9C4 308300FF */  andi       $v1, $a0, 0xFF
    /* 3FF58 800EA9C8 24020001 */  addiu      $v0, $zero, 0x1
    /* 3FF5C 800EA9CC AFBF0018 */  sw         $ra, 0x18($sp)
    /* 3FF60 800EA9D0 10620006 */  beq        $v1, $v0, .L800EA9EC
    /* 3FF64 800EA9D4 01006821 */   addu      $t5, $t0, $zero
    /* 3FF68 800EA9D8 24020002 */  addiu      $v0, $zero, 0x2
    /* 3FF6C 800EA9DC 1062001D */  beq        $v1, $v0, .L800EAA54
    /* 3FF70 800EA9E0 30C2FFFF */   andi      $v0, $a2, 0xFFFF
    /* 3FF74 800EA9E4 0803AAC7 */  j          .L800EAB1C
    /* 3FF78 800EA9E8 31A200FF */   andi      $v0, $t5, 0xFF
  .L800EA9EC:
    /* 3FF7C 800EA9EC 31020002 */  andi       $v0, $t0, 0x2
    /* 3FF80 800EA9F0 1440004A */  bnez       $v0, .L800EAB1C
    /* 3FF84 800EA9F4 31A200FF */   andi      $v0, $t5, 0xFF
    /* 3FF88 800EA9F8 240C0001 */  addiu      $t4, $zero, 0x1
    /* 3FF8C 800EA9FC 30C9FFFF */  andi       $t1, $a2, 0xFFFF
    /* 3FF90 800EAA00 30EAFFFF */  andi       $t2, $a3, 0xFFFF
    /* 3FF94 800EAA04 3C08800F */  lui        $t0, %hi(D_800EB8F4)
    /* 3FF98 800EAA08 2508B8F4 */  addiu      $t0, $t0, %lo(D_800EB8F4)
    /* 3FF9C 800EAA0C 00001821 */  addu       $v1, $zero, $zero
    /* 3FFA0 800EAA10 250B0080 */  addiu      $t3, $t0, 0x80
  .L800EAA14:
    /* 3FFA4 800EAA14 3C02800F */  lui        $v0, %hi(D_800EB8F0)
    /* 3FFA8 800EAA18 00431021 */  addu       $v0, $v0, $v1
    /* 3FFAC 800EAA1C 9042B8F0 */  lbu        $v0, %lo(D_800EB8F0)($v0)
    /* 3FFB0 800EAA20 544C0007 */  bnel       $v0, $t4, .L800EAA40
    /* 3FFB4 800EAA24 25080008 */   addiu     $t0, $t0, 0x8
    /* 3FFB8 800EAA28 3C02800F */  lui        $v0, %hi(D_800EB8F2)
    /* 3FFBC 800EAA2C 00431021 */  addu       $v0, $v0, $v1
    /* 3FFC0 800EAA30 9442B8F2 */  lhu        $v0, %lo(D_800EB8F2)($v0)
    /* 3FFC4 800EAA34 1122002F */  beq        $t1, $v0, .L800EAAF4
    /* 3FFC8 800EAA38 00000000 */   nop
    /* 3FFCC 800EAA3C 25080008 */  addiu      $t0, $t0, 0x8
  .L800EAA40:
    /* 3FFD0 800EAA40 010B102A */  slt        $v0, $t0, $t3
    /* 3FFD4 800EAA44 1440FFF3 */  bnez       $v0, .L800EAA14
    /* 3FFD8 800EAA48 24630008 */   addiu     $v1, $v1, 0x8
    /* 3FFDC 800EAA4C 0803AAC7 */  j          .L800EAB1C
    /* 3FFE0 800EAA50 31A200FF */   andi      $v0, $t5, 0xFF
  .L800EAA54:
    /* 3FFE4 800EAA54 14400014 */  bnez       $v0, .L800EAAA8
    /* 3FFE8 800EAA58 240C0002 */   addiu     $t4, $zero, 0x2
    /* 3FFEC 800EAA5C 240B0001 */  addiu      $t3, $zero, 0x1
    /* 3FFF0 800EAA60 30A900FF */  andi       $t1, $a1, 0xFF
    /* 3FFF4 800EAA64 3C03800F */  lui        $v1, %hi(D_800EB8F0)
    /* 3FFF8 800EAA68 2463B8F0 */  addiu      $v1, $v1, %lo(D_800EB8F0)
    /* 3FFFC 800EAA6C 00004021 */  addu       $t0, $zero, $zero
    /* 40000 800EAA70 246A0080 */  addiu      $t2, $v1, 0x80
  .L800EAA74:
    /* 40004 800EAA74 90620000 */  lbu        $v0, 0x0($v1)
    /* 40008 800EAA78 544B0007 */  bnel       $v0, $t3, .L800EAA98
    /* 4000C 800EAA7C 24630008 */   addiu     $v1, $v1, 0x8
    /* 40010 800EAA80 3C02800F */  lui        $v0, %hi(D_800EB8F1)
    /* 40014 800EAA84 00481021 */  addu       $v0, $v0, $t0
    /* 40018 800EAA88 9042B8F1 */  lbu        $v0, %lo(D_800EB8F1)($v0)
    /* 4001C 800EAA8C 50490001 */  beql       $v0, $t1, .L800EAA94
    /* 40020 800EAA90 A0600000 */   sb        $zero, 0x0($v1)
  .L800EAA94:
    /* 40024 800EAA94 24630008 */  addiu      $v1, $v1, 0x8
  .L800EAA98:
    /* 40028 800EAA98 006A102A */  slt        $v0, $v1, $t2
    /* 4002C 800EAA9C 1440FFF5 */  bnez       $v0, .L800EAA74
    /* 40030 800EAAA0 25080008 */   addiu     $t0, $t0, 0x8
    /* 40034 800EAAA4 240C0002 */  addiu      $t4, $zero, 0x2
  .L800EAAA8:
    /* 40038 800EAAA8 30A900FF */  andi       $t1, $a1, 0xFF
    /* 4003C 800EAAAC 30EAFFFF */  andi       $t2, $a3, 0xFFFF
    /* 40040 800EAAB0 3C08800F */  lui        $t0, %hi(D_800EB8F4)
    /* 40044 800EAAB4 2508B8F4 */  addiu      $t0, $t0, %lo(D_800EB8F4)
    /* 40048 800EAAB8 00001821 */  addu       $v1, $zero, $zero
    /* 4004C 800EAABC 250B0080 */  addiu      $t3, $t0, 0x80
  .L800EAAC0:
    /* 40050 800EAAC0 3C02800F */  lui        $v0, %hi(D_800EB8F0)
    /* 40054 800EAAC4 00431021 */  addu       $v0, $v0, $v1
    /* 40058 800EAAC8 9042B8F0 */  lbu        $v0, %lo(D_800EB8F0)($v0)
    /* 4005C 800EAACC 544C000F */  bnel       $v0, $t4, .L800EAB0C
    /* 40060 800EAAD0 25080008 */   addiu     $t0, $t0, 0x8
    /* 40064 800EAAD4 3C02800F */  lui        $v0, %hi(D_800EB8F1)
    /* 40068 800EAAD8 00431021 */  addu       $v0, $v0, $v1
    /* 4006C 800EAADC 9042B8F1 */  lbu        $v0, %lo(D_800EB8F1)($v0)
    /* 40070 800EAAE0 5522000A */  bnel       $t1, $v0, .L800EAB0C
    /* 40074 800EAAE4 25080008 */   addiu     $t0, $t0, 0x8
    /* 40078 800EAAE8 3C01800F */  lui        $at, %hi(D_800EB8F2)
    /* 4007C 800EAAEC 00230821 */  addu       $at, $at, $v1
    /* 40080 800EAAF0 A426B8F2 */  sh         $a2, %lo(D_800EB8F2)($at)
  .L800EAAF4:
    /* 40084 800EAAF4 95020000 */  lhu        $v0, 0x0($t0)
    /* 40088 800EAAF8 004A102B */  sltu       $v0, $v0, $t2
    /* 4008C 800EAAFC 5440000D */  bnel       $v0, $zero, .L800EAB34
    /* 40090 800EAB00 A5070000 */   sh        $a3, 0x0($t0)
    /* 40094 800EAB04 0803AACD */  j          .L800EAB34
    /* 40098 800EAB08 00000000 */   nop
  .L800EAB0C:
    /* 4009C 800EAB0C 010B102A */  slt        $v0, $t0, $t3
    /* 400A0 800EAB10 1440FFEB */  bnez       $v0, .L800EAAC0
    /* 400A4 800EAB14 24630008 */   addiu     $v1, $v1, 0x8
    /* 400A8 800EAB18 31A200FF */  andi       $v0, $t5, 0xFF
  .L800EAB1C:
    /* 400AC 800EAB1C AFA20010 */  sw         $v0, 0x10($sp)
    /* 400B0 800EAB20 308400FF */  andi       $a0, $a0, 0xFF
    /* 400B4 800EAB24 30A500FF */  andi       $a1, $a1, 0xFF
    /* 400B8 800EAB28 30C6FFFF */  andi       $a2, $a2, 0xFFFF
    /* 400BC 800EAB2C 0C03AAD0 */  jal        func_800EAB40
    /* 400C0 800EAB30 30E7FFFF */   andi      $a3, $a3, 0xFFFF
  .L800EAB34:
    /* 400C4 800EAB34 8FBF0018 */  lw         $ra, 0x18($sp)
    /* 400C8 800EAB38 03E00008 */  jr         $ra
    /* 400CC 800EAB3C 27BD0020 */   addiu     $sp, $sp, 0x20
endlabel func_800EA9BC

nonmatching func_800EAB40, 0xE4

glabel func_800EAB40
    /* 400D0 800EAB40 93AD0013 */  lbu        $t5, 0x13($sp)
    /* 400D4 800EAB44 00006021 */  addu       $t4, $zero, $zero
    /* 400D8 800EAB48 00005021 */  addu       $t2, $zero, $zero
    /* 400DC 800EAB4C 3C0B800F */  lui        $t3, %hi(D_800EB8F4)
    /* 400E0 800EAB50 256BB8F4 */  addiu      $t3, $t3, %lo(D_800EB8F4)
    /* 400E4 800EAB54 2569FFFC */  addiu      $t1, $t3, -0x4
    /* 400E8 800EAB58 00004021 */  addu       $t0, $zero, $zero
  .L800EAB5C:
    /* 400EC 800EAB5C 91220000 */  lbu        $v0, 0x0($t1)
    /* 400F0 800EAB60 1440000A */  bnez       $v0, .L800EAB8C
    /* 400F4 800EAB64 000C10C0 */   sll       $v0, $t4, 3
    /* 400F8 800EAB68 A1240000 */  sb         $a0, 0x0($t1)
    /* 400FC 800EAB6C 3C01800F */  lui        $at, %hi(D_800EB8F1)
    /* 40100 800EAB70 00280821 */  addu       $at, $at, $t0
    /* 40104 800EAB74 A025B8F1 */  sb         $a1, %lo(D_800EB8F1)($at)
    /* 40108 800EAB78 3C01800F */  lui        $at, %hi(D_800EB8F2)
    /* 4010C 800EAB7C 00280821 */  addu       $at, $at, $t0
    /* 40110 800EAB80 A426B8F2 */  sh         $a2, %lo(D_800EB8F2)($at)
    /* 40114 800EAB84 0803AB04 */  j          .L800EAC10
    /* 40118 800EAB88 A5670000 */   sh        $a3, 0x0($t3)
  .L800EAB8C:
    /* 4011C 800EAB8C 95630000 */  lhu        $v1, 0x0($t3)
    /* 40120 800EAB90 3C01800F */  lui        $at, %hi(D_800EB8F4)
    /* 40124 800EAB94 00220821 */  addu       $at, $at, $v0
    /* 40128 800EAB98 9422B8F4 */  lhu        $v0, %lo(D_800EB8F4)($at)
    /* 4012C 800EAB9C 0062182B */  sltu       $v1, $v1, $v0
    /* 40130 800EABA0 54600001 */  bnel       $v1, $zero, .L800EABA8
    /* 40134 800EABA4 01406021 */   addu      $t4, $t2, $zero
  .L800EABA8:
    /* 40138 800EABA8 256B0008 */  addiu      $t3, $t3, 0x8
    /* 4013C 800EABAC 25290008 */  addiu      $t1, $t1, 0x8
    /* 40140 800EABB0 254A0001 */  addiu      $t2, $t2, 0x1
    /* 40144 800EABB4 29420010 */  slti       $v0, $t2, 0x10
    /* 40148 800EABB8 1440FFE8 */  bnez       $v0, .L800EAB5C
    /* 4014C 800EABBC 25080008 */   addiu     $t0, $t0, 0x8
    /* 40150 800EABC0 000C40C0 */  sll        $t0, $t4, 3
    /* 40154 800EABC4 3C02800F */  lui        $v0, %hi(D_800EB8F4)
    /* 40158 800EABC8 00481021 */  addu       $v0, $v0, $t0
    /* 4015C 800EABCC 9442B8F4 */  lhu        $v0, %lo(D_800EB8F4)($v0)
    /* 40160 800EABD0 30E3FFFF */  andi       $v1, $a3, 0xFFFF
    /* 40164 800EABD4 0043102B */  sltu       $v0, $v0, $v1
    /* 40168 800EABD8 10400010 */  beqz       $v0, .L800EAC1C
    /* 4016C 800EABDC 00000000 */   nop
    /* 40170 800EABE0 3C01800F */  lui        $at, %hi(D_800EB8F0)
    /* 40174 800EABE4 00280821 */  addu       $at, $at, $t0
    /* 40178 800EABE8 A024B8F0 */  sb         $a0, %lo(D_800EB8F0)($at)
    /* 4017C 800EABEC 3C01800F */  lui        $at, %hi(D_800EB8F1)
    /* 40180 800EABF0 00280821 */  addu       $at, $at, $t0
    /* 40184 800EABF4 A025B8F1 */  sb         $a1, %lo(D_800EB8F1)($at)
    /* 40188 800EABF8 3C01800F */  lui        $at, %hi(D_800EB8F2)
    /* 4018C 800EABFC 00280821 */  addu       $at, $at, $t0
    /* 40190 800EAC00 A426B8F2 */  sh         $a2, %lo(D_800EB8F2)($at)
    /* 40194 800EAC04 3C01800F */  lui        $at, %hi(D_800EB8F4)
    /* 40198 800EAC08 00280821 */  addu       $at, $at, $t0
    /* 4019C 800EAC0C A427B8F4 */  sh         $a3, %lo(D_800EB8F4)($at)
  .L800EAC10:
    /* 401A0 800EAC10 3C01800F */  lui        $at, %hi(D_800EB8F6)
    /* 401A4 800EAC14 00280821 */  addu       $at, $at, $t0
    /* 401A8 800EAC18 A02DB8F6 */  sb         $t5, %lo(D_800EB8F6)($at)
  .L800EAC1C:
    /* 401AC 800EAC1C 03E00008 */  jr         $ra
    /* 401B0 800EAC20 00000000 */   nop
endlabel func_800EAB40

nonmatching func_800EAC24, 0x2F8

glabel func_800EAC24
    /* 401B4 800EAC24 27BDFFD8 */  addiu      $sp, $sp, -0x28
    /* 401B8 800EAC28 AFB20018 */  sw         $s2, 0x18($sp)
    /* 401BC 800EAC2C 24120008 */  addiu      $s2, $zero, 0x8
    /* 401C0 800EAC30 AFB40020 */  sw         $s4, 0x20($sp)
    /* 401C4 800EAC34 24140002 */  addiu      $s4, $zero, 0x2
    /* 401C8 800EAC38 AFB00010 */  sw         $s0, 0x10($sp)
    /* 401CC 800EAC3C 3C10800F */  lui        $s0, %hi(D_800EB970)
    /* 401D0 800EAC40 2610B970 */  addiu      $s0, $s0, %lo(D_800EB970)
    /* 401D4 800EAC44 AFB10014 */  sw         $s1, 0x14($sp)
    /* 401D8 800EAC48 00008821 */  addu       $s1, $zero, $zero
    /* 401DC 800EAC4C AFB3001C */  sw         $s3, 0x1C($sp)
    /* 401E0 800EAC50 26130080 */  addiu      $s3, $s0, 0x80
    /* 401E4 800EAC54 AFBF0024 */  sw         $ra, 0x24($sp)
    /* 401E8 800EAC58 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 401EC 800EAC5C AC20BAF0 */  sw         $zero, %lo(D_800EBAF0)($at)
  .L800EAC60:
    /* 401F0 800EAC60 92020000 */  lbu        $v0, 0x0($s0)
    /* 401F4 800EAC64 5040000F */  beql       $v0, $zero, .L800EACA4
    /* 401F8 800EAC68 26100008 */   addiu     $s0, $s0, 0x8
    /* 401FC 800EAC6C 3C04800F */  lui        $a0, %hi(D_800EB974)
    /* 40200 800EAC70 00912021 */  addu       $a0, $a0, $s1
    /* 40204 800EAC74 0C0206C2 */  jal        func_80081B08
    /* 40208 800EAC78 8C84B974 */   lw        $a0, %lo(D_800EB974)($a0)
    /* 4020C 800EAC7C 14400003 */  bnez       $v0, .L800EAC8C
    /* 40210 800EAC80 00000000 */   nop
    /* 40214 800EAC84 0803AB28 */  j          .L800EACA0
    /* 40218 800EAC88 A2000000 */   sb        $zero, 0x0($s0)
  .L800EAC8C:
    /* 4021C 800EAC8C 3C02800F */  lui        $v0, %hi(D_800EB972)
    /* 40220 800EAC90 00511021 */  addu       $v0, $v0, $s1
    /* 40224 800EAC94 9042B972 */  lbu        $v0, %lo(D_800EB972)($v0)
    /* 40228 800EAC98 A2140000 */  sb         $s4, 0x0($s0)
    /* 4022C 800EAC9C 02429023 */  subu       $s2, $s2, $v0
  .L800EACA0:
    /* 40230 800EACA0 26100008 */  addiu      $s0, $s0, 0x8
  .L800EACA4:
    /* 40234 800EACA4 0213102A */  slt        $v0, $s0, $s3
    /* 40238 800EACA8 1440FFED */  bnez       $v0, .L800EAC60
    /* 4023C 800EACAC 26310008 */   addiu     $s1, $s1, 0x8
    /* 40240 800EACB0 3405FFFF */  ori        $a1, $zero, 0xFFFF
    /* 40244 800EACB4 3C11800F */  lui        $s1, %hi(D_800EB974)
    /* 40248 800EACB8 2631B974 */  addiu      $s1, $s1, %lo(D_800EB974)
    /* 4024C 800EACBC 24100002 */  addiu      $s0, $zero, 0x2
  .L800EACC0:
    /* 40250 800EACC0 0C03AC0A */  jal        func_800EB028
    /* 40254 800EACC4 24040002 */   addiu     $a0, $zero, 0x2
    /* 40258 800EACC8 00404021 */  addu       $t0, $v0, $zero
    /* 4025C 800EACCC 05000030 */  bltz       $t0, .L800EAD90
    /* 40260 800EACD0 000810C0 */   sll       $v0, $t0, 3
    /* 40264 800EACD4 3C05800F */  lui        $a1, %hi(D_800EB8F4)
    /* 40268 800EACD8 00A22821 */  addu       $a1, $a1, $v0
    /* 4026C 800EACDC 94A5B8F4 */  lhu        $a1, %lo(D_800EB8F4)($a1)
    /* 40270 800EACE0 00404821 */  addu       $t1, $v0, $zero
    /* 40274 800EACE4 02203821 */  addu       $a3, $s1, $zero
    /* 40278 800EACE8 00003021 */  addu       $a2, $zero, $zero
  .L800EACEC:
    /* 4027C 800EACEC 3C02800F */  lui        $v0, %hi(D_800EB970)
    /* 40280 800EACF0 00461021 */  addu       $v0, $v0, $a2
    /* 40284 800EACF4 9042B970 */  lbu        $v0, %lo(D_800EB970)($v0)
    /* 40288 800EACF8 5040001D */  beql       $v0, $zero, .L800EAD70
    /* 4028C 800EACFC 24C60008 */   addiu     $a2, $a2, 0x8
    /* 40290 800EAD00 3C03800F */  lui        $v1, %hi(D_800EB971)
    /* 40294 800EAD04 00661821 */  addu       $v1, $v1, $a2
    /* 40298 800EAD08 9063B971 */  lbu        $v1, %lo(D_800EB971)($v1)
    /* 4029C 800EAD0C 3C02800F */  lui        $v0, %hi(D_800EB8F1)
    /* 402A0 800EAD10 00491021 */  addu       $v0, $v0, $t1
    /* 402A4 800EAD14 9042B8F1 */  lbu        $v0, %lo(D_800EB8F1)($v0)
    /* 402A8 800EAD18 14620015 */  bne        $v1, $v0, .L800EAD70
    /* 402AC 800EAD1C 24C60008 */   addiu     $a2, $a2, 0x8
    /* 402B0 800EAD20 3C02800F */  lui        $v0, %hi(D_800EBAF0)
    /* 402B4 800EAD24 8C42BAF0 */  lw         $v0, %lo(D_800EBAF0)($v0)
    /* 402B8 800EAD28 000210C0 */  sll        $v0, $v0, 3
    /* 402BC 800EAD2C 3C01800F */  lui        $at, %hi(D_800EB9F0)
    /* 402C0 800EAD30 00220821 */  addu       $at, $at, $v0
    /* 402C4 800EAD34 AC27B9F0 */  sw         $a3, %lo(D_800EB9F0)($at)
    /* 402C8 800EAD38 3C04800F */  lui        $a0, %hi(D_800EB8F2)
    /* 402CC 800EAD3C 00892021 */  addu       $a0, $a0, $t1
    /* 402D0 800EAD40 9484B8F2 */  lhu        $a0, %lo(D_800EB8F2)($a0)
    /* 402D4 800EAD44 3C01800F */  lui        $at, %hi(D_800EB9F6)
    /* 402D8 800EAD48 00220821 */  addu       $at, $at, $v0
    /* 402DC 800EAD4C A030B9F6 */  sb         $s0, %lo(D_800EB9F6)($at)
    /* 402E0 800EAD50 3C03800F */  lui        $v1, %hi(D_800EBAF0)
    /* 402E4 800EAD54 8C63BAF0 */  lw         $v1, %lo(D_800EBAF0)($v1)
    /* 402E8 800EAD58 24630001 */  addiu      $v1, $v1, 0x1
    /* 402EC 800EAD5C 3C01800F */  lui        $at, %hi(D_800EB9F4)
    /* 402F0 800EAD60 00220821 */  addu       $at, $at, $v0
    /* 402F4 800EAD64 A424B9F4 */  sh         $a0, %lo(D_800EB9F4)($at)
    /* 402F8 800EAD68 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 402FC 800EAD6C AC23BAF0 */  sw         $v1, %lo(D_800EBAF0)($at)
  .L800EAD70:
    /* 40300 800EAD70 28C20080 */  slti       $v0, $a2, 0x80
    /* 40304 800EAD74 1440FFDD */  bnez       $v0, .L800EACEC
    /* 40308 800EAD78 24E70008 */   addiu     $a3, $a3, 0x8
    /* 4030C 800EAD7C 000810C0 */  sll        $v0, $t0, 3
    /* 40310 800EAD80 3C01800F */  lui        $at, %hi(D_800EB8F0)
    /* 40314 800EAD84 00220821 */  addu       $at, $at, $v0
    /* 40318 800EAD88 0803AB30 */  j          .L800EACC0
    /* 4031C 800EAD8C A020B8F0 */   sb        $zero, %lo(D_800EB8F0)($at)
  .L800EAD90:
    /* 40320 800EAD90 3405FFFF */  ori        $a1, $zero, 0xFFFF
    /* 40324 800EAD94 24100001 */  addiu      $s0, $zero, 0x1
    /* 40328 800EAD98 3C11800F */  lui        $s1, %hi(D_800EB974)
    /* 4032C 800EAD9C 2631B974 */  addiu      $s1, $s1, %lo(D_800EB974)
  .L800EADA0:
    /* 40330 800EADA0 0C03AC0A */  jal        func_800EB028
    /* 40334 800EADA4 24040001 */   addiu     $a0, $zero, 0x1
    /* 40338 800EADA8 00404021 */  addu       $t0, $v0, $zero
    /* 4033C 800EADAC 0500004D */  bltz       $t0, .L800EAEE4
    /* 40340 800EADB0 00000000 */   nop
    /* 40344 800EADB4 000820C0 */  sll        $a0, $t0, 3
    /* 40348 800EADB8 3C02800F */  lui        $v0, %hi(D_800EB8F2)
    /* 4034C 800EADBC 00441021 */  addu       $v0, $v0, $a0
    /* 40350 800EADC0 9442B8F2 */  lhu        $v0, %lo(D_800EB8F2)($v0)
    /* 40354 800EADC4 3C05800F */  lui        $a1, %hi(D_800EB8F4)
    /* 40358 800EADC8 00A42821 */  addu       $a1, $a1, $a0
    /* 4035C 800EADCC 94A5B8F4 */  lhu        $a1, %lo(D_800EB8F4)($a1)
    /* 40360 800EADD0 00021842 */  srl        $v1, $v0, 1
    /* 40364 800EADD4 3C01800F */  lui        $at, %hi(D_800EB700)
    /* 40368 800EADD8 00230821 */  addu       $at, $at, $v1
    /* 4036C 800EADDC 9023B700 */  lbu        $v1, %lo(D_800EB700)($at)
    /* 40370 800EADE0 00021027 */  nor        $v0, $zero, $v0
    /* 40374 800EADE4 30420001 */  andi       $v0, $v0, 0x1
    /* 40378 800EADE8 00021080 */  sll        $v0, $v0, 2
    /* 4037C 800EADEC 00431807 */  srav       $v1, $v1, $v0
    /* 40380 800EADF0 3067000F */  andi       $a3, $v1, 0xF
    /* 40384 800EADF4 0247102A */  slt        $v0, $s2, $a3
    /* 40388 800EADF8 10400007 */  beqz       $v0, .L800EAE18
    /* 4038C 800EADFC 00004021 */   addu      $t0, $zero, $zero
    /* 40390 800EAE00 3C02800F */  lui        $v0, %hi(D_800EB8F6)
    /* 40394 800EAE04 00441021 */  addu       $v0, $v0, $a0
    /* 40398 800EAE08 9042B8F6 */  lbu        $v0, %lo(D_800EB8F6)($v0)
    /* 4039C 800EAE0C 30420001 */  andi       $v0, $v0, 0x1
    /* 403A0 800EAE10 10400034 */  beqz       $v0, .L800EAEE4
    /* 403A4 800EAE14 00000000 */   nop
  .L800EAE18:
    /* 403A8 800EAE18 00804821 */  addu       $t1, $a0, $zero
    /* 403AC 800EAE1C 02203021 */  addu       $a2, $s1, $zero
    /* 403B0 800EAE20 3C03800F */  lui        $v1, %hi(D_800EB970)
    /* 403B4 800EAE24 2463B970 */  addiu      $v1, $v1, %lo(D_800EB970)
    /* 403B8 800EAE28 00002021 */  addu       $a0, $zero, $zero
  .L800EAE2C:
    /* 403BC 800EAE2C 90620000 */  lbu        $v0, 0x0($v1)
    /* 403C0 800EAE30 54400024 */  bnel       $v0, $zero, .L800EAEC4
    /* 403C4 800EAE34 24C60008 */   addiu     $a2, $a2, 0x8
    /* 403C8 800EAE38 A0700000 */  sb         $s0, 0x0($v1)
    /* 403CC 800EAE3C 3C02800F */  lui        $v0, %hi(D_800EB8F1)
    /* 403D0 800EAE40 00491021 */  addu       $v0, $v0, $t1
    /* 403D4 800EAE44 9042B8F1 */  lbu        $v0, %lo(D_800EB8F1)($v0)
    /* 403D8 800EAE48 3C01800F */  lui        $at, %hi(D_800EB972)
    /* 403DC 800EAE4C 00240821 */  addu       $at, $at, $a0
    /* 403E0 800EAE50 A027B972 */  sb         $a3, %lo(D_800EB972)($at)
    /* 403E4 800EAE54 3C01800F */  lui        $at, %hi(D_800EB971)
    /* 403E8 800EAE58 00240821 */  addu       $at, $at, $a0
    /* 403EC 800EAE5C A022B971 */  sb         $v0, %lo(D_800EB971)($at)
    /* 403F0 800EAE60 3C02800F */  lui        $v0, %hi(D_800EBAF0)
    /* 403F4 800EAE64 8C42BAF0 */  lw         $v0, %lo(D_800EBAF0)($v0)
    /* 403F8 800EAE68 000210C0 */  sll        $v0, $v0, 3
    /* 403FC 800EAE6C 3C01800F */  lui        $at, %hi(D_800EB9F0)
    /* 40400 800EAE70 00220821 */  addu       $at, $at, $v0
    /* 40404 800EAE74 AC26B9F0 */  sw         $a2, %lo(D_800EB9F0)($at)
    /* 40408 800EAE78 3C04800F */  lui        $a0, %hi(D_800EB8F2)
    /* 4040C 800EAE7C 00892021 */  addu       $a0, $a0, $t1
    /* 40410 800EAE80 9484B8F2 */  lhu        $a0, %lo(D_800EB8F2)($a0)
    /* 40414 800EAE84 3C01800F */  lui        $at, %hi(D_800EB9F6)
    /* 40418 800EAE88 00220821 */  addu       $at, $at, $v0
    /* 4041C 800EAE8C A030B9F6 */  sb         $s0, %lo(D_800EB9F6)($at)
    /* 40420 800EAE90 3C03800F */  lui        $v1, %hi(D_800EBAF0)
    /* 40424 800EAE94 8C63BAF0 */  lw         $v1, %lo(D_800EBAF0)($v1)
    /* 40428 800EAE98 24630001 */  addiu      $v1, $v1, 0x1
    /* 4042C 800EAE9C 3C01800F */  lui        $at, %hi(D_800EB9F4)
    /* 40430 800EAEA0 00220821 */  addu       $at, $at, $v0
    /* 40434 800EAEA4 A424B9F4 */  sh         $a0, %lo(D_800EB9F4)($at)
    /* 40438 800EAEA8 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 4043C 800EAEAC AC23BAF0 */  sw         $v1, %lo(D_800EBAF0)($at)
    /* 40440 800EAEB0 3C01800F */  lui        $at, %hi(D_800EB8F0)
    /* 40444 800EAEB4 00290821 */  addu       $at, $at, $t1
    /* 40448 800EAEB8 A020B8F0 */  sb         $zero, %lo(D_800EB8F0)($at)
    /* 4044C 800EAEBC 0803ABB6 */  j          .L800EAED8
    /* 40450 800EAEC0 02479023 */   subu      $s2, $s2, $a3
  .L800EAEC4:
    /* 40454 800EAEC4 24630008 */  addiu      $v1, $v1, 0x8
    /* 40458 800EAEC8 25080001 */  addiu      $t0, $t0, 0x1
    /* 4045C 800EAECC 29020010 */  slti       $v0, $t0, 0x10
    /* 40460 800EAED0 1440FFD6 */  bnez       $v0, .L800EAE2C
    /* 40464 800EAED4 24840008 */   addiu     $a0, $a0, 0x8
  .L800EAED8:
    /* 40468 800EAED8 29020010 */  slti       $v0, $t0, 0x10
    /* 4046C 800EAEDC 1440FFB0 */  bnez       $v0, .L800EADA0
    /* 40470 800EAEE0 00000000 */   nop
  .L800EAEE4:
    /* 40474 800EAEE4 3C02800F */  lui        $v0, %hi(D_800EBAF0)
    /* 40478 800EAEE8 8C42BAF0 */  lw         $v0, %lo(D_800EBAF0)($v0)
    /* 4047C 800EAEEC 3C038000 */  lui        $v1, (0x80000000 >> 16)
    /* 40480 800EAEF0 00431025 */  or         $v0, $v0, $v1
    /* 40484 800EAEF4 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 40488 800EAEF8 AC22BAF0 */  sw         $v0, %lo(D_800EBAF0)($at)
    /* 4048C 800EAEFC 8FBF0024 */  lw         $ra, 0x24($sp)
    /* 40490 800EAF00 8FB40020 */  lw         $s4, 0x20($sp)
    /* 40494 800EAF04 8FB3001C */  lw         $s3, 0x1C($sp)
    /* 40498 800EAF08 8FB20018 */  lw         $s2, 0x18($sp)
    /* 4049C 800EAF0C 8FB10014 */  lw         $s1, 0x14($sp)
    /* 404A0 800EAF10 8FB00010 */  lw         $s0, 0x10($sp)
    /* 404A4 800EAF14 03E00008 */  jr         $ra
    /* 404A8 800EAF18 27BD0028 */   addiu     $sp, $sp, 0x28
endlabel func_800EAC24

nonmatching func_800EAF1C, 0x10C

glabel func_800EAF1C
    /* 404AC 800EAF1C 3C03800F */  lui        $v1, %hi(D_800EBAF0)
    /* 404B0 800EAF20 8C63BAF0 */  lw         $v1, %lo(D_800EBAF0)($v1)
    /* 404B4 800EAF24 27BDFFC8 */  addiu      $sp, $sp, -0x38
    /* 404B8 800EAF28 AFBF0030 */  sw         $ra, 0x30($sp)
    /* 404BC 800EAF2C AFB5002C */  sw         $s5, 0x2C($sp)
    /* 404C0 800EAF30 AFB40028 */  sw         $s4, 0x28($sp)
    /* 404C4 800EAF34 AFB30024 */  sw         $s3, 0x24($sp)
    /* 404C8 800EAF38 AFB20020 */  sw         $s2, 0x20($sp)
    /* 404CC 800EAF3C AFB1001C */  sw         $s1, 0x1C($sp)
    /* 404D0 800EAF40 04610030 */  bgez       $v1, .L800EB004
    /* 404D4 800EAF44 AFB00018 */   sw        $s0, 0x18($sp)
    /* 404D8 800EAF48 3C027FFF */  lui        $v0, (0x7FFFFFFF >> 16)
    /* 404DC 800EAF4C 3442FFFF */  ori        $v0, $v0, (0x7FFFFFFF & 0xFFFF)
    /* 404E0 800EAF50 00621024 */  and        $v0, $v1, $v0
    /* 404E4 800EAF54 3C01800F */  lui        $at, %hi(D_800EBAF0)
    /* 404E8 800EAF58 AC22BAF0 */  sw         $v0, %lo(D_800EBAF0)($at)
    /* 404EC 800EAF5C 10400029 */  beqz       $v0, .L800EB004
    /* 404F0 800EAF60 00009021 */   addu      $s2, $zero, $zero
    /* 404F4 800EAF64 24150001 */  addiu      $s5, $zero, 0x1
    /* 404F8 800EAF68 24140002 */  addiu      $s4, $zero, 0x2
    /* 404FC 800EAF6C 3C10800F */  lui        $s0, %hi(D_800EB9F4)
    /* 40500 800EAF70 2610B9F4 */  addiu      $s0, $s0, %lo(D_800EB9F4)
    /* 40504 800EAF74 2611FFFC */  addiu      $s1, $s0, -0x4
    /* 40508 800EAF78 00009821 */  addu       $s3, $zero, $zero
  .L800EAF7C:
    /* 4050C 800EAF7C 3C02800F */  lui        $v0, %hi(D_800EB9F6)
    /* 40510 800EAF80 00531021 */  addu       $v0, $v0, $s3
    /* 40514 800EAF84 9042B9F6 */  lbu        $v0, %lo(D_800EB9F6)($v0)
    /* 40518 800EAF88 10550005 */  beq        $v0, $s5, .L800EAFA0
    /* 4051C 800EAF8C 00000000 */   nop
    /* 40520 800EAF90 1054000C */  beq        $v0, $s4, .L800EAFC4
    /* 40524 800EAF94 00000000 */   nop
    /* 40528 800EAF98 0803ABFA */  j          .L800EAFE8
    /* 4052C 800EAF9C 26100008 */   addiu     $s0, $s0, 0x8
  .L800EAFA0:
    /* 40530 800EAFA0 3C048010 */  lui        $a0, %hi(D_80104710)
    /* 40534 800EAFA4 0C02077C */  jal        func_80081DF0
    /* 40538 800EAFA8 24844710 */   addiu     $a0, $a0, %lo(D_80104710)
    /* 4053C 800EAFAC 96040000 */  lhu        $a0, 0x0($s0)
    /* 40540 800EAFB0 0C0205DC */  jal        func_80081770
    /* 40544 800EAFB4 26100008 */   addiu     $s0, $s0, 0x8
    /* 40548 800EAFB8 8E230000 */  lw         $v1, 0x0($s1)
    /* 4054C 800EAFBC 0803ABFA */  j          .L800EAFE8
    /* 40550 800EAFC0 AC620000 */   sw        $v0, 0x0($v1)
  .L800EAFC4:
    /* 40554 800EAFC4 96030000 */  lhu        $v1, 0x0($s0)
    /* 40558 800EAFC8 8E240000 */  lw         $a0, 0x0($s1)
    /* 4055C 800EAFCC 2C620002 */  sltiu      $v0, $v1, 0x2
    /* 40560 800EAFD0 14400002 */  bnez       $v0, .L800EAFDC
    /* 40564 800EAFD4 24050002 */   addiu     $a1, $zero, 0x2
    /* 40568 800EAFD8 00602821 */  addu       $a1, $v1, $zero
  .L800EAFDC:
    /* 4056C 800EAFDC 8C840000 */  lw         $a0, 0x0($a0)
    /* 40570 800EAFE0 0C020695 */  jal        func_80081A54
    /* 40574 800EAFE4 26100008 */   addiu     $s0, $s0, 0x8
  .L800EAFE8:
    /* 40578 800EAFE8 26310008 */  addiu      $s1, $s1, 0x8
    /* 4057C 800EAFEC 3C02800F */  lui        $v0, %hi(D_800EBAF0)
    /* 40580 800EAFF0 8C42BAF0 */  lw         $v0, %lo(D_800EBAF0)($v0)
    /* 40584 800EAFF4 26520001 */  addiu      $s2, $s2, 0x1
    /* 40588 800EAFF8 0242102B */  sltu       $v0, $s2, $v0
    /* 4058C 800EAFFC 1440FFDF */  bnez       $v0, .L800EAF7C
    /* 40590 800EB000 26730008 */   addiu     $s3, $s3, 0x8
  .L800EB004:
    /* 40594 800EB004 8FBF0030 */  lw         $ra, 0x30($sp)
    /* 40598 800EB008 8FB5002C */  lw         $s5, 0x2C($sp)
    /* 4059C 800EB00C 8FB40028 */  lw         $s4, 0x28($sp)
    /* 405A0 800EB010 8FB30024 */  lw         $s3, 0x24($sp)
    /* 405A4 800EB014 8FB20020 */  lw         $s2, 0x20($sp)
    /* 405A8 800EB018 8FB1001C */  lw         $s1, 0x1C($sp)
    /* 405AC 800EB01C 8FB00018 */  lw         $s0, 0x18($sp)
    /* 405B0 800EB020 03E00008 */  jr         $ra
    /* 405B4 800EB024 27BD0038 */   addiu     $sp, $sp, 0x38
endlabel func_800EAF1C

nonmatching func_800EB028, 0x80

glabel func_800EB028
    /* 405B8 800EB028 2408FFFF */  addiu      $t0, $zero, -0x1
    /* 405BC 800EB02C 00004821 */  addu       $t1, $zero, $zero
    /* 405C0 800EB030 00003021 */  addu       $a2, $zero, $zero
    /* 405C4 800EB034 308400FF */  andi       $a0, $a0, 0xFF
    /* 405C8 800EB038 30A5FFFF */  andi       $a1, $a1, 0xFFFF
    /* 405CC 800EB03C 00003821 */  addu       $a3, $zero, $zero
  .L800EB040:
    /* 405D0 800EB040 3C02800F */  lui        $v0, %hi(D_800EB8F0)
    /* 405D4 800EB044 00471021 */  addu       $v0, $v0, $a3
    /* 405D8 800EB048 9042B8F0 */  lbu        $v0, %lo(D_800EB8F0)($v0)
    /* 405DC 800EB04C 54440011 */  bnel       $v0, $a0, .L800EB094
    /* 405E0 800EB050 24C60001 */   addiu     $a2, $a2, 0x1
    /* 405E4 800EB054 3C03800F */  lui        $v1, %hi(D_800EB8F4)
    /* 405E8 800EB058 00671821 */  addu       $v1, $v1, $a3
    /* 405EC 800EB05C 9463B8F4 */  lhu        $v1, %lo(D_800EB8F4)($v1)
    /* 405F0 800EB060 00A3102B */  sltu       $v0, $a1, $v1
    /* 405F4 800EB064 5440000B */  bnel       $v0, $zero, .L800EB094
    /* 405F8 800EB068 24C60001 */   addiu     $a2, $a2, 0x1
    /* 405FC 800EB06C 11200007 */  beqz       $t1, .L800EB08C
    /* 40600 800EB070 000810C0 */   sll       $v0, $t0, 3
    /* 40604 800EB074 3C01800F */  lui        $at, %hi(D_800EB8F4)
    /* 40608 800EB078 00220821 */  addu       $at, $at, $v0
    /* 4060C 800EB07C 9422B8F4 */  lhu        $v0, %lo(D_800EB8F4)($at)
    /* 40610 800EB080 0043102B */  sltu       $v0, $v0, $v1
    /* 40614 800EB084 50400003 */  beql       $v0, $zero, .L800EB094
    /* 40618 800EB088 24C60001 */   addiu     $a2, $a2, 0x1
  .L800EB08C:
    /* 4061C 800EB08C 00C04021 */  addu       $t0, $a2, $zero
    /* 40620 800EB090 24C60001 */  addiu      $a2, $a2, 0x1
  .L800EB094:
    /* 40624 800EB094 28C20010 */  slti       $v0, $a2, 0x10
    /* 40628 800EB098 1440FFE9 */  bnez       $v0, .L800EB040
    /* 4062C 800EB09C 24E70008 */   addiu     $a3, $a3, 0x8
    /* 40630 800EB0A0 03E00008 */  jr         $ra
    /* 40634 800EB0A4 01001021 */   addu      $v0, $t0, $zero
endlabel func_800EB028
    /* 40638 800EB0A8 00000000 */  nop
    /* 4063C 800EB0AC 00000000 */  nop
