#include <cstdint>
#include <cstdio>

#include "recomp.h"
#include "librecomp/overlays.hpp"

#include "bank_overlays.hpp"

// Declarations of the bank unit's recompiled functions (`func_ovl_*`). Its
// symbols are namespaced so they cannot collide with the main unit's overlay-C
// symbols, which sit at the same RAM addresses in a different bank.
#include "../BankFuncs/funcs.h"

namespace ogre {
namespace {

struct BankRecord {
    uint32_t rom_start;
    int32_t ram_start;
    uint32_t size;
    const recomp::overlays::BankFunctionEntry* funcs;
    size_t num_funcs;
};

// Generated by tools/gen_bank_funcs.py from BankFuncs/recomp_overlays.inl.
#include "bank_funcs.inc"

// The game copies a record in 0x200-byte chunks; register it once, on the first
// chunk. The runtime keeps the authoritative "is this RAM resident" state.
void on_streamed_dma(uint32_t rom_offset, uint32_t ram_addr, uint32_t /*size*/) {
    for (const BankRecord& record : kBankRecords) {
        if (rom_offset < record.rom_start || rom_offset >= record.rom_start + record.size) {
            continue;
        }

        // Chunks of one record keep a constant ROM->RAM delta.
        uint32_t expected_ram = (uint32_t)record.ram_start + (rom_offset - record.rom_start);
        if (ram_addr != expected_ram) {
            continue;
        }

        if (recomp::overlays::is_function_bank_loaded(record.ram_start)) {
            return;
        }

        printf("[bank] loading overlay record rom=0x%06X ram=0x%08X size=0x%X (%zu functions)\n",
               record.rom_start, (uint32_t)record.ram_start, record.size, record.num_funcs);
        fflush(stdout);

        recomp::overlays::load_function_bank(record.ram_start, record.size, record.funcs,
                                             record.num_funcs);
        return;
    }
}

}  // namespace

void register_bank_overlays() {
    recomp::overlays::set_streamed_dma_hook(on_streamed_dma);
    printf("[bank] %zu streamed-overlay record(s), %zu function(s) armed\n",
           ARRLEN(kBankRecords),
           (size_t)(sizeof(kBankRec2Functions) / sizeof(kBankRec2Functions[0]) +
                    sizeof(kBankRec3Functions) / sizeof(kBankRec3Functions[0]) +
                    sizeof(kBankRec6Functions) / sizeof(kBankRec6Functions[0])));
    fflush(stdout);
}

}  // namespace ogre
