#include <chrono>
#include <csignal>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "recomp.h"
#include "librecomp/overlays.hpp"
#include "ultramodern/ultramodern.hpp"

#include "bank_overlays.hpp"

namespace ogre {
namespace {

#if !defined(__EMSCRIPTEN__)
// A cross-bank crash (a bank loaded over another bank's RAM, with a stale or
// compile-time-bound function still running) dies with a raw SIGSEGV, where the
// recompiled call stack is lost because the build omits frame pointers. The
// runtime keeps a shadow per-thread call chain, so print it here.
void on_fatal_signal(int sig, siginfo_t* info, void* /*uctx*/) {
    uint8_t* rdram = ultramodern::get_rdram_base();
    PTR(OSThread) self = (rdram != nullptr) ? ultramodern::this_thread() : (PTR(OSThread))0;
    const int tid = (self != 0) ? TO_PTR(OSThread, self)->id : -1;
    const void* fault = (info != nullptr) ? info->si_addr : nullptr;
    // Guest words live at rdram + (addr - 0x80000000), so the host fault minus
    // the base reads back as the faulting N64 address (half/byte accesses xor
    // the low bits; see recomp_mem_addr in recomp.h).
    const uint64_t offset = (fault != nullptr && rdram != nullptr)
        ? (uint64_t)((const uint8_t*)fault - rdram) : 0;
    fprintf(stderr, "[crash] signal %d on N64 thread %d fault=%p rdram=%p offset=0x%llX\n",
            sig, tid, fault, (const void*)rdram, (unsigned long long)offset);
    fflush(stderr);
    ultramodern::debug_dump_call_chain(tid, "crash");
    for (int t = 1; t < 32; t++) {
        const uint32_t func = ultramodern::debug_last_func_vram(t);
        if (func != 0) {
            fprintf(stderr, "[crash]   t%-3d last func 0x%08X\n", t, func);
        }
    }
    ultramodern::debug_dump_chain_history();
    // OGRE_DUMP_RDRAM=<path>: same whole-RDRAM dump as the exit_after path, so
    // a crash's data pointers can be followed offline instead of guessed.
    if (const char* dump_path = getenv("OGRE_DUMP_RDRAM")) {
        if (rdram != nullptr) {
            if (FILE* f = fopen(dump_path, "wb")) {
                const size_t size = 0x800000;
                size_t written = fwrite(rdram, 1, size, f);
                fclose(f);
                fprintf(stderr, "[crash] dumped %zu bytes of rdram to %s\n", written, dump_path);
            } else {
                fprintf(stderr, "[crash] could not open %s for rdram dump\n", dump_path);
            }
        }
    }
    fflush(stdout);
    fflush(stderr);
    std::signal(sig, SIG_DFL);
    std::raise(sig);
}
#endif

struct BankRecord {
    uint32_t rom_start;
    int32_t ram_start;
    uint32_t size;  // ROM bytes DMA'd (== .size in the section table)
    // RAM end (exclusive) from the game's segment table; [ram_start + size,
    // ram_end) is BSS the loader zeroes on every load. Chunk-DMA records that
    // are not segment-table entries carry ram_end == ram_start + size.
    int32_t ram_end;
    const recomp::overlays::BankFunctionEntry* funcs;
    size_t num_funcs;
};

// Generated by tools/gen_bank_funcs.py from BankFuncs/recomp_overlays.inl.
#include "bank_funcs.inc"

// Every streamed-overlay record in the game's segment table (ROM 0x387C0): one
// 0x28-byte entry per record, { ram_start, ram_end, rom_start, rom_end, ... }.
// Only the records in kBankRecords are recompiled so far; this table is purely
// so a run reports *which* uncompiled bank the game tried to load, which is how
// the next record set to compile is chosen.
struct StreamedRecord {
    uint32_t rom_start;
    int32_t ram_start;
    uint32_t rom_size;
    bool compiled;  // already recompiled (bank unit or the main unit's overlay C)
};

static const StreamedRecord kAllStreamedRecords[] = {
    { 0x066E30u, (int32_t)0x80197B90u, 0x002AF0u, true  },  //  0 (bank unit E)
    { 0x06E680u, (int32_t)0x80197B90u, 0x002C20u, true  },  //  1 (bank unit D)
    { 0x0E4910u, (int32_t)0x80197B90u, 0x0072C0u, true  },  //  2 (bank unit)
    { 0x0EBBD0u, (int32_t)0x8019EE70u, 0x00E440u, true  },  //  3 (bank unit)
    { 0x0FA010u, (int32_t)0x8019EE70u, 0x0005E0u, true  },  //  4 (bank unit C)
    { 0x0FA5F0u, (int32_t)0x8019EE70u, 0x000010u, false },  //  5
    { 0x0FA600u, (int32_t)0x801AD5C0u, 0x007700u, true  },  //  6 (bank unit)
    { 0x101D00u, (int32_t)0x801AD5C0u, 0x043530u, false },  //  7
    { 0x145230u, (int32_t)0x801F4050u, 0x0099D0u, false },  //  8
    { 0x14EC00u, (int32_t)0x801FDA90u, 0x0173E0u, false },  //  9
    { 0x1F0A00u, (int32_t)0x801AD5C0u, 0x0230E0u, true  },  // 10 (bank unit C)
    { 0x24BC70u, (int32_t)0x801F7100u, 0x0131F0u, true  },  // 11 (bank unit C)
    { 0x25EE60u, (int32_t)0x8020A300u, 0x0169C0u, true  },  // 12 (bank unit C)
    { 0x275820u, (int32_t)0x802210E0u, 0x0047D0u, true  },  // 13 (bank unit C)
    { 0x281830u, (int32_t)0x802258B0u, 0x005370u, true  },  // 14 (bank unit C)
    { 0x1CE040u, (int32_t)0x80197B90u, 0x0229C0u, true  },  // 15 (main unit, overlay C)
    { 0x279FF0u, (int32_t)0x802258B0u, 0x007840u, false },  // 16
    { 0x069920u, (int32_t)0x80197B90u, 0x004D60u, true  },  // 17 (bank unit B)
    { 0x1BA020u, (int32_t)0x80220F60u, 0x0092B0u, true  },  // 18 (bank unit B)
};

// Boot straight into a screen.
//
// `OGRE_SCENE=<name|hex>` (or the original `OGRE_FORCE_SCENE=<hex>`) jumps to a
// scene instead of waiting out the attract loop (which takes minutes). The
// attract scene dispatcher (asm/1060.s @0x80075DB8) uses the u16 at
// `*(u16*)(D_800C4BBC + 4)` as the current scene id every frame and derives
// everything else -- the per-scene update function and the bank it loads --
// from it, so poking that word makes the game load and run the scene normally.
// The poke repeats until `D_800E810E` reports the scene active, and only starts
// after `OGRE_SCENE_AFTER_MS` (default 3000) so boot/init can settle.
//
// The names are the scenes this project has identified so far; a hex id can
// always be given instead. `OGRE_SCENE_TRACE=1` logs every scene change
// (`[scene] id=0x.. descriptor=0x.. mask=0x..`), which is how new names are
// found: run the attract loop and read the log.
struct SceneName {
    const char* name;
    uint16_t id;
};

// Scene ids verified against captures (session 36; the visuals for each id are
// recorded in docs/HANDOFF-2026-09-14-session36.md). `0x18`/`0x02` still crash:
// their update functions need the unfinished cross-bank work (sessions 33/34).
static const SceneName kScenes[] = {
    { "title", 0x0004 },      // attract title: prologue text, then the logo + the New Game / Tutorial / Stereo menu over the scrolling clouds
    { "intro", 0x0009 },      // boot intro: soldiers, falling cube, Nintendo 64 logo
    { "publishers", 0x000A }, // Licensed by Nintendo / ATLUS / QUEST
    { "story", 0x000B },      // world-map story attract
    { "unit-info", 0x000C },  // the unit-description book
    { "tutorial", 0x0017 },   // title menu -> Tutorial: Deneb's "Is this your first time here?" dialogue (session 43)
    { "menu", 0x0018 },       // title menu sub-screen (record 1) - crashes until the cross-bank work lands
    { "new-game", 0x0002 },   // New Game loader (records 0/14) - one frame, then 0x0D
};

static bool scene_lookup(const char* spec, uint16_t& id) {
    for (const SceneName& scene : kScenes) {
        if (strcmp(spec, scene.name) == 0) {
            id = scene.id;
            return true;
        }
    }
    char* end = nullptr;
    const unsigned long value = strtoul(spec, &end, 16);
    if ((end != spec) && (*end == '\0') && (value <= 0xFFFFu)) {
        id = (uint16_t)value;
        return true;
    }
    return false;
}

// --- scene forcing --------------------------------------------------------
//
// The dispatcher is `func_80075BC0` (asm/1060.s @0x80075DB8). Each call:
//   1. copies the pending id `D_800E8214` into the current scene-state block
//      (`*(u16*)(*(u32*)D_800C4BBC + 4)`), then
//   2. runs the block's id as the scene.
// So writing *either* word can select a scene, but only inside a narrow window:
// once the boot has entered its first real scene (0x09 at ~1.1 s) the running
// scene's own update function owns the block and re-establishes it every frame,
// and a poke is simply overwritten. A late poke therefore does nothing, which
// is why the default `OGRE_SCENE_AFTER_MS` is 0 and why poking *every* frame
// forever corrupts the state machine.
//
// The poke is retried from `poll_scene` (per frame, main thread) as well as
// from `force_scene_on_load` (the streamed-DMA hook, i.e. from inside a scene
// update) until `D_800E810E` reports the target active, then released.

struct ForcedScene {
    bool configured = false;
    uint16_t id = 0;
};

const ForcedScene& forced_scene() {
    static const ForcedScene forced = [] {
        ForcedScene f;
        const char* spec = getenv("OGRE_SCENE");
        if (spec == nullptr) {
            spec = getenv("OGRE_FORCE_SCENE");
        }
        if (spec == nullptr) {
            return f;
        }
        if (!scene_lookup(spec, f.id) || f.id == 0) {
            fprintf(stderr, "[scene] unknown scene '%s' (use a name from the table or a hex id)\n",
                    spec);
            return f;
        }
        f.configured = true;
        return f;
    }();
    return forced;
}

// Delay before the first poke. The window in which a poke takes effect is at
// the *start* of the run (before ~1 s), so this defaults to 0; it exists only
// for A/B runs that want to reproduce the old delayed behaviour.
uint32_t scene_after_ms() {
    static const uint32_t value = [] {
        const char* v = getenv("OGRE_SCENE_AFTER_MS");
        if (v == nullptr) {
            v = getenv("OGRE_FORCE_SCENE_AFTER_MS");
        }
        return (v != nullptr) ? (uint32_t)strtoul(v, nullptr, 10) : 0u;
    }();
    return value;
}

uint32_t scene_elapsed_ms() {
    return (uint32_t)std::chrono::duration_cast<std::chrono::milliseconds>(
               ultramodern::time_since_start())
        .count();
}

// The id the dispatcher is currently running (`D_800E810E`), or 0xFFFF when the
// game is not up yet.
uint16_t active_scene_id() {
    uint8_t* rdram = ultramodern::get_rdram_base();
    if (rdram == nullptr) {
        return 0xFFFF;
    }
    return (uint16_t)MEM_HU(0x0000, (gpr)(int32_t)0x800E810E);
}

// True once the target is the running scene. Latched: the attract loop may
// advance past it later and the forcing must not drag it back.
bool forced_scene_active(const ForcedScene& forced) {
    static bool seen = false;
    if (!forced.configured) {
        return false;
    }
    if (!seen && (active_scene_id() == forced.id)) {
        seen = true;
        fprintf(stderr, "[scene] forced scene 0x%02X is active\n", forced.id);
        fflush(stderr);
    }
    return seen;
}

// Write both words the dispatcher reads: the state block's id (seen when the
// poke lands inside a scene update) and the pending id (copied into the block
// at the top of every dispatcher call, so it is what a main-thread poke uses).
bool poke_scene(uint16_t id) {
    uint8_t* rdram = ultramodern::get_rdram_base();
    if (rdram == nullptr) {
        return false;
    }
    const uint32_t block = (uint32_t)MEM_W(0x0, (gpr)(int32_t)0x800C4BBC);
    if (block >= 0x80000000u && block < 0x80800000u) {
        MEM_H(0x4, (gpr)(int32_t)block) = id;
    }
    MEM_H(0x0, (gpr)(int32_t)0x800E8214) = id;
    return true;
}

}  // namespace

// The poke itself, run from the streamed-DMA hook: a bank load during a scene
// update is the one moment the dispatcher is inside its loop and will re-read
// the block id. `poll_scene` retries it per frame for the boot window.
void force_scene_on_load() {
    const ForcedScene& forced = forced_scene();
    if (!forced.configured || forced_scene_active(forced)) {
        return;
    }
    if (scene_elapsed_ms() < scene_after_ms()) {
        return;
    }
    static bool announced = false;
    if (!announced && poke_scene(forced.id)) {
        announced = true;
        printf("[scene] forcing scene 0x%02X\n", forced.id);
        fflush(stdout);
    }
}

// OGRE_SCENE_LOG=1: log every scene change. This is how the names in kScenes
// are found and verified. Also the retry half of the scene forcing above: the
// streamed-DMA hook rarely fires inside the boot window, so the per-frame path
// re-applies the poke until the dispatcher agrees.
void poll_scene() {
    const ForcedScene& forced = forced_scene();
    if (forced.configured && !forced_scene_active(forced) &&
        (scene_elapsed_ms() >= scene_after_ms())) {
        poke_scene(forced.id);
    }

    // OGRE_SCENE_TRACE=1: the forcing state every ~500 ms: what the dispatcher
    // reports active, the pending word this pass writes, and what the state
    // block currently holds. "forcing the id but the block never shows it" and
    // "the block shows it but the dispatcher ignores it" are different bugs.
    if (getenv("OGRE_SCENE_TRACE") != nullptr) {
        static uint32_t last_trace = 0;
        if (scene_elapsed_ms() - last_trace >= 500) {
            last_trace = scene_elapsed_ms();
            uint8_t* rdram = ultramodern::get_rdram_base();
            if (rdram != nullptr) {
                const uint32_t block = (uint32_t)MEM_W(0x0, (gpr)(int32_t)0x800C4BBC);
                const uint16_t block_id = (block >= 0x80000000u && block < 0x80800000u)
                                              ? (uint16_t)MEM_HU(0x4, (gpr)(int32_t)block)
                                              : 0xFFFF;
                fprintf(stderr,
                        "[scene-trace] t=%ums active=0x%04X pending(D_800E8214)=0x%04X "
                        "block=0x%08X block->id=0x%04X forced=0x%04X done=%d\n",
                        scene_elapsed_ms(), active_scene_id(),
                        (uint16_t)MEM_HU(0x0, (gpr)(int32_t)0x800E8214), block, block_id,
                        forced.configured ? forced.id : 0, (int)forced_scene_active(forced));
                fflush(stderr);
            }
        }
    }

    static const bool trace = (getenv("OGRE_SCENE_LOG") != nullptr);
    if (!trace) {
        return;
    }
    uint8_t* rdram = ultramodern::get_rdram_base();
    if (rdram == nullptr) {
        return;
    }
    static uint16_t last = 0;
    static bool first = true;
    const uint16_t now = active_scene_id();
    if (!first && (now == last)) {
        return;
    }
    first = false;
    last = now;
    // The descriptor word is only meaningful while a scene is active: during
    // boot the game leaves a stale, non-KSEG0 value there, and dereferencing it
    // (descriptor + 0x10) walks off RDRAM and dies with SIGBUS. Validate it.
    const uint32_t descriptor = (uint32_t)MEM_W(0x0, (gpr)(int32_t)0x800E8294);
    const bool in_rdram = (descriptor >= 0x80000000u) && (descriptor < 0x80800000u) &&
                          (descriptor + 0x14u >= descriptor);
    const uint32_t mask = in_rdram ? (uint32_t)MEM_W(0x10, (gpr)(int32_t)descriptor) : 0;
    fprintf(stderr, "[scene] t=%lldms id=0x%04X descriptor=0x%08X mask=0x%08X\n",
            (long long)scene_elapsed_ms(), now, descriptor, mask);
    fflush(stderr);
}

namespace {

// The game copies a record in 0x200-byte chunks; register it once, on the first
// chunk. The runtime keeps the authoritative "is this RAM resident" state.
void on_streamed_dma(uint32_t rom_offset, uint32_t ram_addr, uint32_t /*size*/) {
    // Scene loads are the moments the dispatcher is guaranteed to be looking at
    // the id, so the poke lives here (the original behaviour). Poking every
    // frame instead corrupts the scene state machine: the game rewrites the id
    // itself and a running scene then sees a state that does not match it.
    force_scene_on_load();

    for (const BankRecord& record : kBankRecords) {
        if (rom_offset < record.rom_start || rom_offset >= record.rom_start + record.size) {
            continue;
        }

        // Chunks of one record keep a constant ROM->RAM delta.
        uint32_t expected_ram = (uint32_t)record.ram_start + (rom_offset - record.rom_start);
        if (ram_addr != expected_ram) {
            continue;
        }

        if (recomp::overlays::is_function_bank_loaded(record.rom_start)) {
            return;
        }

        printf("[bank] loading overlay record rom=0x%06X ram=0x%08X size=0x%X (%zu functions)\n",
               record.rom_start, (uint32_t)record.ram_start, record.size, record.num_funcs);
        fflush(stdout);

        recomp::overlays::load_function_bank(record.rom_start, record.ram_start, record.size,
                                             record.funcs, record.num_funcs);
        // The hardware loader zeroes [ram_start + size, ram_end) as BSS. The
        // port must do the same: scene 0x0D's init reads those ranges as
        // empty lists/tables, and stale bytes from whatever occupied the RAM
        // before walk as wild pointers (bad asset ids, list corruption).
        // Evicting the span also drops bank-map entries for code that no
        // longer lives there, the same as the ROM span above.
        const uint32_t bss_start = (uint32_t)record.ram_start + record.size;
        const uint32_t bss_end = (uint32_t)record.ram_end;
        if (bss_end > bss_start) {
            uint8_t* rdram = ultramodern::get_rdram_base();
            if (rdram != nullptr) {
                recomp::overlays::unload_overlapping_overlays((int32_t)bss_start,
                                                              bss_end - bss_start);
                memset(rdram + (bss_start - 0x80000000u), 0, bss_end - bss_start);
            }
        }
        return;
    }

    // Diagnostic: the game loaded a streamed record that is not recompiled yet.
    // The untouched stub then returns without doing anything, which is how a
    // screen (e.g. the "unit info" scene) ends up bouncing straight back to the
    // title. Reported once per record so a long unattended run names the bank.
    static bool reported[ARRLEN(kAllStreamedRecords)] = {};
    for (size_t r = 0; r < ARRLEN(kAllStreamedRecords); r++) {
        const StreamedRecord& record = kAllStreamedRecords[r];
        if (record.compiled) {
            continue;
        }
        if (rom_offset < record.rom_start || rom_offset >= record.rom_start + record.rom_size) {
            continue;
        }
        if (ram_addr != (uint32_t)record.ram_start + (rom_offset - record.rom_start)) {
            continue;
        }
        if (!reported[r]) {
            reported[r] = true;
            printf("[bank] UNCOMPILED streamed record %zu: rom=0x%06X ram=0x%08X size=0x%X\n",
                   r, record.rom_start, (uint32_t)record.ram_start, record.rom_size);
            // The scene dispatcher (asm/1060.s @0x80075E50) stores the current
            // scene id at D_800E810E and its descriptor at D_800E8294; the
            // descriptor's +0x10 word is the record mask handed to the loader
            // func_800761E4. Dumping it names the bank the game actually asked
            // for, which is how the next record set is chosen.
            uint8_t* rdram = ultramodern::get_rdram_base();
            if (rdram != nullptr) {
                uint16_t scene = MEM_H(0x0000, (gpr)(int32_t)0x800E810E);
                uint32_t desc = (uint32_t)MEM_W(0x0, (gpr)(int32_t)0x800E8294);
                uint32_t mask = (desc != 0) ? (uint32_t)MEM_W(0x10, (gpr)(int32_t)desc) : 0;
                printf("[bank]   scene=0x%04X descriptor=0x%08X record mask=0x%08X\n",
                       scene, desc, mask);
            }
            fflush(stdout);
        }
        return;
    }
}

}  // namespace

void register_bank_overlays() {
#if !defined(__EMSCRIPTEN__)
    struct sigaction sa = {};
    sa.sa_sigaction = on_fatal_signal;
    sigemptyset(&sa.sa_mask);
    sa.sa_flags = SA_SIGINFO | SA_RESETHAND;
    sigaction(SIGSEGV, &sa, nullptr);
    sigaction(SIGBUS, &sa, nullptr);
    sigaction(SIGABRT, &sa, nullptr);
#endif
    recomp::overlays::set_streamed_dma_hook(on_streamed_dma);

    size_t total_functions = 0;
    for (const BankRecord& record : kBankRecords) {
        total_functions += record.num_funcs;
    }
    printf("[bank] %zu streamed-overlay record(s), %zu function(s) armed\n",
           ARRLEN(kBankRecords), total_functions);
    fflush(stdout);
}

}  // namespace ogre
