#!/usr/bin/env python3
"""Generate app/src/bank_funcs.inc from the bank unit's recomp_overlays.inl.

The bank unit (see config-bank.yaml / config-bank.toml) recompiles streamed
overlay records at their true RAM addresses. Its `recomp_overlays.inl` already
contains the per-record function tables, but the app cannot include it directly:
it defines `section_table`/`num_sections`, which the main unit's copy also
defines.

Instead this script flattens it into a minimal, self-contained table:

    static const recomp::overlays::BankFunctionEntry kBank<Name>Functions[] = {
        { <absolute ram address>, func_ovl_<ram address> }, ...
    };
    static const BankRecord kBankRecords[] = {
        { <rom start>, <ram start>, <size>, kBank<Name>Functions, N }, ...
    };

which app/src/bank_overlays.cpp uses to register a record's functions when the
game DMA's it, and to drop them when another bank overwrites that RAM.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SECTION_TABLE_RE = re.compile(
    r"\{\s*\.rom_addr\s*=\s*0x([0-9A-Fa-f]+),\s*\.ram_addr\s*=\s*0x([0-9A-Fa-f]+),"
    r"\s*\.size\s*=\s*0x([0-9A-Fa-f]+),\s*\.funcs\s*=\s*(\w+),"
)
FUNC_ENTRY_RE = re.compile(
    r"\{\s*\.func\s*=\s*(\w+),\s*\.offset\s*=\s*0x([0-9A-Fa-f]+),"
    r"\s*\.rom_size\s*=\s*0x([0-9A-Fa-f]+)\s*\}"
)
FUNCS_ARRAY_RE = re.compile(r"static FuncEntry (\w+)\[\]\s*=\s*\{")


def table_name(funcs_array: str) -> str:
    """section_2_bankRec2_funcs -> kBankRec2Functions"""
    suffix = re.sub(r"^section_\d+_", "", funcs_array)
    suffix = re.sub(r"_funcs$", "", suffix)
    suffix = re.sub(r"^bank", "", suffix)
    return f"kBank{suffix}Functions"


def parse_func_arrays(text: str) -> dict[str, list[tuple[str, int]]]:
    """name -> [(func_symbol, offset), ...]"""
    arrays: dict[str, list[tuple[str, int]]] = {}
    current: str | None = None
    for line in text.splitlines():
        m = FUNCS_ARRAY_RE.search(line)
        if m:
            current = m.group(1)
            arrays[current] = []
            continue
        if current is None:
            continue
        if line.strip() == "};":
            current = None
            continue
        m = FUNC_ENTRY_RE.search(line)
        if m:
            arrays[current].append((m.group(1), int(m.group(2), 16)))
    return arrays


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    inl_path = root / "BankFuncs" / "recomp_overlays.inl"
    out_path = root / "app" / "src" / "bank_funcs.inc"

    if not inl_path.exists():
        print(f"gen_bank_funcs: {inl_path} not found (run `make bank-recomp`)", file=sys.stderr)
        return 1

    text = inl_path.read_text()
    arrays = parse_func_arrays(text)

    records: list[tuple[int, int, int, str]] = []
    for m in SECTION_TABLE_RE.finditer(text):
        rom, ram, size, funcs = int(m.group(1), 16), int(m.group(2), 16), int(m.group(3), 16), m.group(4)
        if funcs not in arrays:
            print(f"gen_bank_funcs: missing function array {funcs}", file=sys.stderr)
            return 1
        records.append((rom, ram, size, funcs))

    if not records:
        print("gen_bank_funcs: no sections found in recomp_overlays.inl", file=sys.stderr)
        return 1

    out: list[str] = [
        "// GENERATED by tools/gen_bank_funcs.py from BankFuncs/recomp_overlays.inl.",
        "// Do not edit by hand; run `make bank-recomp`.",
        "",
    ]

    for rom, ram, size, funcs in records:
        # section_<elf index>_<segment name>_funcs -> kBank<SegmentName>Functions
        table = table_name(funcs)
        out.append(f"static const recomp::overlays::BankFunctionEntry {table}[] = {{")
        for sym, offset in arrays[funcs]:
            out.append(f"    {{ (int32_t)0x{ram + offset:08X}u, {sym} }},")
        out.append("};")
        out.append("")

    out.append("static const BankRecord kBankRecords[] = {")
    for rom, ram, size, funcs in records:
        table = table_name(funcs)
        out.append(
            f"    {{ 0x{rom:08X}u, (int32_t)0x{ram:08X}u, 0x{size:08X}u, "
            f"{table}, ARRLEN({table}) }},"
        )
    out.append("};")
    out.append("")

    out_path.write_text("\n".join(out))
    total = sum(len(arrays[f]) for _, _, _, f in records)
    print(
        "gen_bank_funcs: wrote %s (%d record(s), %d function(s))"
        % (out_path.relative_to(root), len(records), total)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
