#!/usr/bin/env python3
"""Generate app/src/bank_funcs.inc from the bank units' recomp_overlays.inl files.

Each bank unit (config-bank<U>.yaml / .toml, built by `make bank-recomp`)
recompiles a set of streamed-overlay records at their true RAM addresses, with
its own `ovl<U>_` symbol namespace so the units can be linked alongside each
other and the main unit.

The app cannot include a unit's `recomp_overlays.inl` directly: it defines
`section_table`/`num_sections`, which the main unit's copy also defines. Instead
this script flattens every `Bank*Funcs/recomp_overlays.inl` into one
self-contained table:

    extern "C" void <function>(uint8_t*, recomp_context*);      // declarations
    static const recomp::overlays::BankFunctionEntry k<U>_<seg>Functions[] = {
        { <absolute ram address>, <function> }, ...
    };
    static const BankRecord kBankRecords[] = {
        { <rom start>, <ram start>, <size>, k<U>_<seg>Functions, N }, ...
    };

app/src/bank_overlays.cpp uses it to register a record's functions when the game
DMA's it, and to drop them when another bank overwrites that RAM.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

SECTION_TABLE_RE = re.compile(
    r"\{\s*\.rom_addr\s*=\s*0x([0-9A-Fa-f]+),\s*\.ram_addr\s*=\s*0x([0-9A-Fa-f]+),"
    r"\s*\.size\s*=\s*0x([0-9A-Fa-f]+),\s*\.funcs\s*=\s*(\w+),"
)
FUNC_ENTRY_RE = re.compile(
    r"\{\s*\.func\s*=\s*(\w+),\s*\.offset\s*=\s*0x([0-9A-Fa-f]+),"
    r"\s*\.rom_size\s*=\s*0x([0-9A-Fa-f]+)\s*\}"
)
FUNCS_ARRAY_RE = re.compile(r"static FuncEntry (\w+)\[\]\s*=\s*\{")


def parse_func_arrays(text: str) -> dict[str, list[tuple[str, int]]]:
    """name -> [(func_symbol, offset), ...]"""
    arrays: dict[str, list[tuple[str, int]]] = {}
    current: str | None = None
    for line in text.splitlines():
        m = FUNCS_ARRAY_RE.search(line)
        if m:
            current = m.group(1)
            arrays[current] = []
            continue
        if current is None:
            continue
        if line.strip() == "};":
            current = None
            continue
        m = FUNC_ENTRY_RE.search(line)
        if m:
            arrays[current].append((m.group(1), int(m.group(2), 16)))
    return arrays


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    out_path = root / "app" / "src" / "bank_funcs.inc"

    unit_dirs = sorted(p for p in root.glob("Bank*Funcs") if p.is_dir())
    if not unit_dirs:
        print("gen_bank_funcs: no Bank*Funcs/ dirs (run `make bank-recomp`)", file=sys.stderr)
        return 1

    # rom, ram, size, table name
    records: list[tuple[int, int, int, str]] = []
    declarations: dict[str, None] = {}
    tables: list[str] = []
    total_funcs = 0

    for unit_dir in unit_dirs:
        inl = unit_dir / "recomp_overlays.inl"
        if not inl.exists():
            print(f"gen_bank_funcs: {inl} missing", file=sys.stderr)
            return 1

        # BankAFuncs -> A
        unit = re.sub(r"Funcs$", "", re.sub(r"^Bank", "", unit_dir.name))

        text = inl.read_text()
        arrays = parse_func_arrays(text)

        for m in SECTION_TABLE_RE.finditer(text):
            rom = int(m.group(1), 16)
            ram = int(m.group(2), 16)
            size = int(m.group(3), 16)
            funcs = m.group(4)
            if funcs not in arrays:
                print(f"gen_bank_funcs: {inl}: missing function array {funcs}", file=sys.stderr)
                return 1

            seg = re.sub(r"_funcs$", "", re.sub(r"^section_\d+_", "", funcs))
            table = f"k{unit}_{seg}Functions"

            tables.append(f"static const recomp::overlays::BankFunctionEntry {table}[] = {{")
            for sym, offset in arrays[funcs]:
                declarations.setdefault(
                    sym, f'extern "C" void {sym}(uint8_t* rdram, recomp_context* ctx);'
                )
                tables.append(f"    {{ (int32_t)0x{ram + offset:08X}u, {sym} }},")
            tables.append("};")
            tables.append("")

            records.append((rom, ram, size, table))
            total_funcs += len(arrays[funcs])

    if not records:
        print("gen_bank_funcs: no sections found", file=sys.stderr)
        return 1

    out: list[str] = [
        "// GENERATED by tools/gen_bank_funcs.py from Bank*Funcs/recomp_overlays.inl.",
        "// Do not edit by hand; run `make bank-recomp`.",
        "",
        *sorted(declarations.values()),
        "",
        *tables,
        "static const BankRecord kBankRecords[] = {",
    ]
    for rom, ram, size, table in records:
        out.append(
            f"    {{ 0x{rom:08X}u, (int32_t)0x{ram:08X}u, 0x{size:08X}u, "
            f"{table}, ARRLEN({table}) }},"
        )
    out.append("};")
    out.append("")

    out_path.write_text("\n".join(out))
    print(
        "gen_bank_funcs: wrote %s (%d unit(s), %d record(s), %d function(s))"
        % (out_path.relative_to(root), len(unit_dirs), len(records), total_funcs)
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
